---
# Baseline seed for scenario 03.
# Existing management network is in secure range.

- hosts: ndfc
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    fabric_name: cisco_test_fabric1

  tasks:
    - name: Keep management network in secure range
      cisco.dcnm.dcnm_network:
        fabric: "{{ fabric_name }}"
        state: merged
        config:
          - net_name: MGMT_OOB_NET3901
            vrf_name: PROD_VRF_Core
            net_id: 33901
            net_template: Default_Network_Universal
            net_extension_template: Default_Network_Extension_Universal
            vlan_id: 3901
            gw_ip_subnet: "10.39.1.1/24"
        deploy: false
