---
# This playbook can be used to execute integration tests for
# the role located in:
#
# tests/integration/targets/dcnm_image_policy
#
# Modify the hosts and vars sections with details for your testing
# setup and uncomment the testcase you want to run.
#
- name: DCNM VRF tests
  hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    switch_username: admin
    switch_password: "admin!@#"
    ansible_it_fabric: cisco_test_fabric1
    ansible_switch1: 192.168.10.211
    ansible_switch2: 192.168.10.212
    ansible_peer1_ip: 192.168.10.212
    ansible_peer2_ip: 192.168.10.211

    # Variables required by dcnm_vrf tests
    fabric_1: cisco_test_fabric1
    switch_1: 192.168.10.211
    switch_2: 192.168.10.212
    switch_3: 192.168.10.213
    interface_1: Ethernet1/1
    interface_2: Ethernet1/2
    interface_3: Ethernet1/3
    interface_2a: Ethernet1/4
    interface_3a: Ethernet1/5

    ## Uncomment ONE of the following testcases
    # testcase: deleted
    testcase: merged
    # testcase: query

  roles:
    - dcnm_vrf
