# -*- coding: utf-8 -*-
# @author: Allen Robel
# @file: plugins/module_utils/vrf/vrf_playbook_model.py
# Copyright (c) 2020-2023 Cisco and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# pylint: disable=wrong-import-position
"""
Validation model for controller response to the following endpoint when the fabric type is Easy_Fabric (VXLAN_EVPN):

- Verb: GET
- Path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{fabricName}
"""
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class ControllerResponseFabricsEasyFabricGetNvPairs(BaseModel):
    """
    # Summary

    Model representing the nvPairs configuration in the controller response for the following endpoint
    when the fabric type is Easy_Fabric (VXLAN_EVPN):

    - Verb: GET
    - Path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{fabricName}

    # Raises

    ValueError if validation fails
    """

    AAA_REMOTE_IP_ENABLED: Optional[str] = Field(None, description="AAA remote IP enabled")
    AAA_SERVER_CONF: Optional[str] = Field(None, description="AAA server configuration")
    ACTIVE_MIGRATION: Optional[str] = Field(None, description="Active migration")
    ADVERTISE_PIP_BGP: Optional[str] = Field(None, description="Advertise PIP BGP")
    ADVERTISE_PIP_ON_BORDER: Optional[str] = Field(None, description="Advertise PIP on border")
    AGENT_INTF: Optional[str] = Field(None, description="Agent interface")
    AGG_ACC_VPC_PO_ID_RANGE: Optional[str] = Field(None, description="Aggregate access VPC PO ID range")
    AI_ML_QOS_POLICY: Optional[str] = Field(None, description="AI/ML QoS policy")
    ALLOW_L3VNI_NO_VLAN: Optional[str] = Field(None, description="Allow L3VNI no VLAN")
    ALLOW_L3VNI_NO_VLAN_PREV: Optional[str] = Field(None, description="Allow L3VNI no VLAN previous")
    ALLOW_NXC: Optional[str] = Field(None, description="Allow NXC")
    ALLOW_NXC_PREV: Optional[str] = Field(None, description="Allow NXC previous")
    ANYCAST_BGW_ADVERTISE_PIP: Optional[str] = Field(None, description="Anycast BGW advertise PIP")
    ANYCAST_GW_MAC: Optional[str] = Field(None, description="Anycast GW MAC")
    ANYCAST_LB_ID: Optional[str] = Field(None, description="Anycast LB ID")
    ANYCAST_RP_IP_RANGE: Optional[str] = Field(None, description="Anycast RP IP range")
    ANYCAST_RP_IP_RANGE_INTERNAL: Optional[str] = Field(None, description="Anycast RP IP range internal")
    AUTO_SYMMETRIC_DEFAULT_VRF: Optional[str] = Field(None, description="Auto symmetric default VRF")
    AUTO_SYMMETRIC_VRF_LITE: Optional[str] = Field(None, description="Auto symmetric VRF lite")
    AUTO_UNIQUE_VRF_LITE_IP_PREFIX: Optional[str] = Field(None, description="Auto unique VRF lite IP prefix")
    AUTO_UNIQUE_VRF_LITE_IP_PREFIX_PREV: Optional[str] = Field(None, description="Auto unique VRF lite IP prefix previous")
    AUTO_VRFLITE_IFC_DEFAULT_VRF: Optional[str] = Field(None, description="Auto VRF lite interface default VRF")
    BANNER: Optional[str] = Field(None, description="Banner")
    BFD_AUTH_ENABLE: Optional[str] = Field(None, description="BFD authentication enable")
    BFD_AUTH_KEY: Optional[str] = Field(None, description="BFD authentication key")
    BFD_AUTH_KEY_ID: Optional[str] = Field(None, description="BFD authentication key ID")
    BFD_ENABLE: Optional[str] = Field(None, description="BFD enable")
    BFD_ENABLE_PREV: Optional[str] = Field(None, description="BFD enable previous")
    BFD_IBGP_ENABLE: Optional[str] = Field(None, description="BFD iBGP enable")
    BFD_ISIS_ENABLE: Optional[str] = Field(None, description="BFD ISIS enable")
    BFD_OSPF_ENABLE: Optional[str] = Field(None, description="BFD OSPF enable")
    BFD_PIM_ENABLE: Optional[str] = Field(None, description="BFD PIM enable")
    BGP_AS: str = Field(..., min_length=1, description="BGP AS")
    BGP_AS_PREV: Optional[str] = Field(None, description="BGP AS previous")
    BGP_AUTH_ENABLE: Optional[str] = Field(None, description="BGP authentication enable")
    BGP_AUTH_KEY: Optional[str] = Field(None, description="BGP authentication key")
    BGP_AUTH_KEY_TYPE: Optional[str] = Field(None, description="BGP authentication key type")
    BGP_LB_ID: Optional[str] = Field(None, description="BGP LB ID")
    BOOTSTRAP_CONF: Optional[str] = Field(None, description="Bootstrap configuration")
    BOOTSTRAP_ENABLE: Optional[str] = Field(None, description="Bootstrap enable")
    BOOTSTRAP_ENABLE_PREV: Optional[str] = Field(None, description="Bootstrap enable previous")
    BOOTSTRAP_MULTISUBNET: Optional[str] = Field(None, description="Bootstrap multi-subnet")
    BOOTSTRAP_MULTISUBNET_INTERNAL: Optional[str] = Field(None, description="Bootstrap multi-subnet internal")
    BRFIELD_DEBUG_FLAG: Optional[str] = Field(None, description="BR field debug flag")
    BROWNFIELD_NETWORK_NAME_FORMAT: Optional[str] = Field(None, description="Brownfield network name format")
    BROWNFIELD_SKIP_OVERLAY_NETWORK_ATTACHMENTS: Optional[str] = Field(None, description="Brownfield skip overlay network attachments")
    CDP_ENABLE: Optional[str] = Field(None, description="CDP enable")
    COPP_POLICY: Optional[str] = Field(None, description="COPP policy")
    DCI_MACSEC_ALGORITHM: Optional[str] = Field(None, description="DCI MACsec algorithm")
    DCI_MACSEC_CIPHER_SUITE: Optional[str] = Field(None, description="DCI MACsec cipher suite")
    DCI_MACSEC_FALLBACK_ALGORITHM: Optional[str] = Field(None, description="DCI MACsec fallback algorithm")
    DCI_MACSEC_FALLBACK_KEY_STRING: Optional[str] = Field(None, description="DCI MACsec fallback key string")
    DCI_MACSEC_KEY_STRING: Optional[str] = Field(None, description="DCI MACsec key string")
    DCI_SUBNET_RANGE: Optional[str] = Field(None, description="DCI subnet range")
    DCI_SUBNET_TARGET_MASK: Optional[str] = Field(None, description="DCI subnet target mask")
    DEAFULT_QUEUING_POLICY_CLOUDSCALE: Optional[str] = Field(None, description="Default queuing policy CloudScale")
    DEAFULT_QUEUING_POLICY_OTHER: Optional[str] = Field(None, description="Default queuing policy other")
    DEAFULT_QUEUING_POLICY_R_SERIES: Optional[str] = Field(None, description="Default queuing policy R-series")
    DEFAULT_VRF_REDIS_BGP_RMAP: Optional[str] = Field(None, description="Default VRF Redis BGP route map")
    DEPLOYMENT_FREEZE: Optional[str] = Field(None, description="Deployment freeze")
    DHCP_ENABLE: Optional[str] = Field(None, description="DHCP enable")
    DHCP_END: Optional[str] = Field(None, description="DHCP end")
    DHCP_END_INTERNAL: Optional[str] = Field(None, description="DHCP end internal")
    DHCP_IPV6_ENABLE: Optional[str] = Field(None, description="DHCP IPv6 enable")
    DHCP_IPV6_ENABLE_INTERNAL: Optional[str] = Field(None, description="DHCP IPv6 enable internal")
    DHCP_START: Optional[str] = Field(None, description="DHCP start")
    DHCP_START_INTERNAL: Optional[str] = Field(None, description="DHCP start internal")
    DNS_SERVER_IP_LIST: Optional[str] = Field(None, description="DNS server IP list")
    DNS_SERVER_VRF: Optional[str] = Field(None, description="DNS server VRF")
    DOMAIN_NAME_INTERNAL: Optional[str] = Field(None, description="Domain name internal")
    ENABLE_AAA: Optional[str] = Field(None, description="Enable AAA")
    ENABLE_AGENT: Optional[str] = Field(None, description="Enable agent")
    ENABLE_AGG_ACC_ID_RANGE: Optional[str] = Field(None, description="Enable aggregate access ID range")
    ENABLE_AI_ML_QOS_POLICY: Optional[str] = Field(None, description="Enable AI/ML QoS policy")
    ENABLE_AI_ML_QOS_POLICY_FLAP: Optional[str] = Field(None, description="Enable AI/ML QoS policy flap")
    ENABLE_DCI_MACSEC: Optional[str] = Field(None, description="Enable DCI MACsec")
    ENABLE_DCI_MACSEC_PREV: Optional[str] = Field(None, description="Enable DCI MACsec previous")
    ENABLE_DEFAULT_QUEUING_POLICY: Optional[str] = Field(None, description="Enable default queuing policy")
    ENABLE_EVPN: Optional[str] = Field(None, description="Enable EVPN")
    ENABLE_FABRIC_VPC_DOMAIN_ID: Optional[str] = Field(None, description="Enable fabric VPC domain ID")
    ENABLE_FABRIC_VPC_DOMAIN_ID_PREV: Optional[str] = Field(None, description="Enable fabric VPC domain ID previous")
    ENABLE_L3VNI_NO_VLAN: Optional[str] = Field(None, description="Enable L3VNI no VLAN")
    ENABLE_MACSEC: Optional[str] = Field(None, description="Enable MACsec")
    ENABLE_MACSEC_PREV: Optional[str] = Field(None, description="Enable MACsec previous")
    ENABLE_NETFLOW: Optional[str] = Field(None, description="Enable NetFlow")
    ENABLE_NETFLOW_PREV: Optional[str] = Field(None, description="Enable NetFlow previous")
    ENABLE_NGOAM: Optional[str] = Field(None, description="Enable NGOAM")
    ENABLE_NXAPI: Optional[str] = Field(None, description="Enable NXAPI")
    ENABLE_NXAPI_HTTP: Optional[str] = Field(None, description="Enable NXAPI HTTP")
    ENABLE_PBR: Optional[str] = Field(None, description="Enable PBR")
    ENABLE_PVLAN: Optional[str] = Field(None, description="Enable PVLAN")
    ENABLE_PVLAN_PREV: Optional[str] = Field(None, description="Enable PVLAN previous")
    ENABLE_QKD: Optional[str] = Field(None, description="Enable QKD")
    ENABLE_RT_INTF_STATS: Optional[str] = Field(None, description="Enable RT interface stats")
    ENABLE_SGT: Optional[str] = Field(None, description="Enable SGT")
    ENABLE_SGT_PREV: Optional[str] = Field(None, description="Enable SGT previous")
    ENABLE_TENANT_DHCP: Optional[str] = Field(None, description="Enable tenant DHCP")
    ENABLE_TRM: Optional[str] = Field(None, description="Enable TRM")
    ENABLE_TRMv6: Optional[str] = Field(None, description="Enable TRMv6")
    ENABLE_VPC_PEER_LINK_NATIVE_VLAN: Optional[str] = Field(None, description="Enable VPC peer link native VLAN")
    ENABLE_VRI_ID_REALLOC: Optional[str] = Field(None, description="Enable VRI ID reallocation")
    EXTRA_CONF_INTRA_LINKS: Optional[str] = Field(None, description="Extra config intra links")
    EXTRA_CONF_LEAF: Optional[str] = Field(None, description="Extra config leaf")
    EXTRA_CONF_SPINE: Optional[str] = Field(None, description="Extra config spine")
    EXTRA_CONF_TOR: Optional[str] = Field(None, description="Extra config ToR")
    EXT_FABRIC_TYPE: Optional[str] = Field(None, description="External fabric type")
    FABRIC_INTERFACE_TYPE: Optional[str] = Field(None, description="Fabric interface type")
    FABRIC_MTU: Optional[str] = Field(None, description="Fabric MTU")
    FABRIC_MTU_PREV: Optional[str] = Field(None, description="Fabric MTU previous")
    FABRIC_NAME: str = Field(..., description="Fabric name")
    FABRIC_TYPE: Optional[str] = Field(None, description="Fabric type")
    FABRIC_VPC_DOMAIN_ID: Optional[str] = Field(None, description="Fabric VPC domain ID")
    FABRIC_VPC_DOMAIN_ID_PREV: Optional[str] = Field(None, description="Fabric VPC domain ID previous")
    FABRIC_VPC_QOS: Optional[str] = Field(None, description="Fabric VPC QoS")
    FABRIC_VPC_QOS_POLICY_NAME: Optional[str] = Field(None, description="Fabric VPC QoS policy name")
    FEATURE_PTP: Optional[str] = Field(None, description="Feature PTP")
    FEATURE_PTP_INTERNAL: Optional[str] = Field(None, description="Feature PTP internal")
    FF: Optional[str] = Field(None, description="FF")
    GRFIELD_DEBUG_FLAG: Optional[str] = Field(None, description="GR field debug flag")
    HD_TIME: Optional[str] = Field(None, description="HD time")
    HOST_INTF_ADMIN_STATE: Optional[str] = Field(None, description="Host interface admin state")
    IBGP_PEER_TEMPLATE: Optional[str] = Field(None, description="iBGP peer template")
    IBGP_PEER_TEMPLATE_LEAF: Optional[str] = Field(None, description="iBGP peer template leaf")
    IGNORE_CERT: Optional[str] = Field(None, description="Ignore certificate")
    INBAND_DHCP_SERVERS: Optional[str] = Field(None, description="Inband DHCP servers")
    INBAND_MGMT: Optional[str] = Field(None, description="Inband management")
    INBAND_MGMT_PREV: Optional[str] = Field(None, description="Inband management previous")
    INTF_STAT_LOAD_INTERVAL: Optional[str] = Field(None, description="Interface stat load interval")
    IPv6_ANYCAST_RP_IP_RANGE: Optional[str] = Field(None, description="IPv6 anycast RP IP range")
    IPv6_ANYCAST_RP_IP_RANGE_INTERNAL: Optional[str] = Field(None, description="IPv6 anycast RP IP range internal")
    IPv6_MULTICAST_GROUP_SUBNET: Optional[str] = Field(None, description="IPv6 multicast group subnet")
    ISIS_AREA_NUM: Optional[str] = Field(None, description="ISIS area number")
    ISIS_AREA_NUM_PREV: Optional[str] = Field(None, description="ISIS area number previous")
    ISIS_AUTH_ENABLE: Optional[str] = Field(None, description="ISIS authentication enable")
    ISIS_AUTH_KEY: Optional[str] = Field(None, description="ISIS authentication key")
    ISIS_AUTH_KEYCHAIN_KEY_ID: Optional[str] = Field(None, description="ISIS authentication keychain key ID")
    ISIS_AUTH_KEYCHAIN_NAME: Optional[str] = Field(None, description="ISIS authentication keychain name")
    ISIS_LEVEL: Optional[str] = Field(None, description="ISIS level")
    ISIS_OVERLOAD_ELAPSE_TIME: Optional[str] = Field(None, description="ISIS overload elapse time")
    ISIS_OVERLOAD_ENABLE: Optional[str] = Field(None, description="ISIS overload enable")
    ISIS_P2P_ENABLE: Optional[str] = Field(None, description="ISIS P2P enable")
    KME_SERVER_IP: Optional[str] = Field(None, description="KME server IP")
    KME_SERVER_PORT: Optional[str] = Field(None, description="KME server port")
    L2_HOST_INTF_MTU: Optional[str] = Field(None, description="L2 host interface MTU")
    L2_HOST_INTF_MTU_PREV: Optional[str] = Field(None, description="L2 host interface MTU previous")
    L2_SEGMENT_ID_RANGE: Optional[str] = Field(None, description="L2 segment ID range")
    L3VNI_IPv6_MCAST_GROUP: Optional[str] = Field(None, description="L3VNI IPv6 multicast group")
    L3VNI_MCAST_GROUP: Optional[str] = Field(None, description="L3VNI multicast group")
    L3_PARTITION_ID_RANGE: Optional[str] = Field(None, description="L3 partition ID range")
    LINK_STATE_ROUTING: Optional[str] = Field(None, description="Link state routing")
    LINK_STATE_ROUTING_TAG: Optional[str] = Field(None, description="Link state routing tag")
    LINK_STATE_ROUTING_TAG_PREV: Optional[str] = Field(None, description="Link state routing tag previous")
    LOOPBACK0_IPV6_RANGE: Optional[str] = Field(None, description="Loopback0 IPv6 range")
    LOOPBACK0_IP_RANGE: Optional[str] = Field(None, description="Loopback0 IP range")
    LOOPBACK1_IPV6_RANGE: Optional[str] = Field(None, description="Loopback1 IPv6 range")
    LOOPBACK1_IP_RANGE: Optional[str] = Field(None, description="Loopback1 IP range")
    MACSEC_ALGORITHM: Optional[str] = Field(None, description="MACsec algorithm")
    MACSEC_CIPHER_SUITE: Optional[str] = Field(None, description="MACsec cipher suite")
    MACSEC_FALLBACK_ALGORITHM: Optional[str] = Field(None, description="MACsec fallback algorithm")
    MACSEC_FALLBACK_KEY_STRING: Optional[str] = Field(None, description="MACsec fallback key string")
    MACSEC_KEY_STRING: Optional[str] = Field(None, description="MACsec key string")
    MACSEC_REPORT_TIMER: Optional[str] = Field(None, description="MACsec report timer")
    MGMT_GW: Optional[str] = Field(None, description="Management gateway")
    MGMT_GW_INTERNAL: Optional[str] = Field(None, description="Management gateway internal")
    MGMT_PREFIX: Optional[str] = Field(None, description="Management prefix")
    MGMT_PREFIX_INTERNAL: Optional[str] = Field(None, description="Management prefix internal")
    MGMT_V6PREFIX: Optional[str] = Field(None, description="Management V6 prefix")
    MGMT_V6PREFIX_INTERNAL: Optional[str] = Field(None, description="Management V6 prefix internal")
    MPLS_HANDOFF: Optional[str] = Field(None, description="MPLS handoff")
    MPLS_ISIS_AREA_NUM: Optional[str] = Field(None, description="MPLS ISIS area number")
    MPLS_ISIS_AREA_NUM_PREV: Optional[str] = Field(None, description="MPLS ISIS area number previous")
    MPLS_LB_ID: Optional[str] = Field(None, description="MPLS LB ID")
    MPLS_LOOPBACK_IP_RANGE: Optional[str] = Field(None, description="MPLS loopback IP range")
    MSO_CONNECTIVITY_DEPLOYED: Optional[str] = Field(None, description="MSO connectivity deployed")
    MSO_CONTROLER_ID: Optional[str] = Field(None, description="MSO controller ID")
    MSO_SITE_GROUP_NAME: Optional[str] = Field(None, description="MSO site group name")
    MSO_SITE_ID: Optional[str] = Field(None, description="MSO site ID")
    MST_INSTANCE_RANGE: Optional[str] = Field(None, description="MST instance range")
    MULTICAST_GROUP_SUBNET: Optional[str] = Field(None, description="Multicast group subnet")
    MVPN_VRI_ID_RANGE: Optional[str] = Field(None, description="MVPN VRI ID range")
    NETFLOW_EXPORTER_LIST: Optional[str] = Field(None, description="NetFlow exporter list")
    NETFLOW_MONITOR_LIST: Optional[str] = Field(None, description="NetFlow monitor list")
    NETFLOW_RECORD_LIST: Optional[str] = Field(None, description="NetFlow record list")
    NETWORK_VLAN_RANGE: Optional[str] = Field(None, description="Network VLAN range")
    NTP_SERVER_IP_LIST: Optional[str] = Field(None, description="NTP server IP list")
    NTP_SERVER_VRF: Optional[str] = Field(None, description="NTP server VRF")
    NVE_LB_ID: Optional[str] = Field(None, description="NVE LB ID")
    NXAPI_HTTPS_PORT: Optional[str] = Field(None, description="NXAPI HTTPS port")
    NXAPI_HTTP_PORT: Optional[str] = Field(None, description="NXAPI HTTP port")
    NXC_DEST_VRF: Optional[str] = Field(None, description="NXC destination VRF")
    NXC_PROXY_PORT: Optional[str] = Field(None, description="NXC proxy port")
    NXC_PROXY_SERVER: Optional[str] = Field(None, description="NXC proxy server")
    NXC_SRC_INTF: Optional[str] = Field(None, description="NXC source interface")
    OBJECT_TRACKING_NUMBER_RANGE: Optional[str] = Field(None, description="Object tracking number range")
    OSPF_AREA_ID: Optional[str] = Field(None, description="OSPF area ID")
    OSPF_AUTH_ENABLE: Optional[str] = Field(None, description="OSPF authentication enable")
    OSPF_AUTH_KEY: Optional[str] = Field(None, description="OSPF authentication key")
    OSPF_AUTH_KEY_ID: Optional[str] = Field(None, description="OSPF authentication key ID")
    OVERLAY_MODE: Optional[str] = Field(None, description="Overlay mode")
    OVERLAY_MODE_PREV: Optional[str] = Field(None, description="Overlay mode previous")
    OVERWRITE_GLOBAL_NXC: Optional[str] = Field(None, description="Overwrite global NXC")
    PER_VRF_LOOPBACK_AUTO_PROVISION: Optional[str] = Field(None, description="Per VRF loopback auto provision")
    PER_VRF_LOOPBACK_AUTO_PROVISION_PREV: Optional[str] = Field(None, description="Per VRF loopback auto provision previous")
    PER_VRF_LOOPBACK_AUTO_PROVISION_V6: Optional[str] = Field(None, description="Per VRF loopback auto provision V6")
    PER_VRF_LOOPBACK_AUTO_PROVISION_V6_PREV: Optional[str] = Field(None, description="Per VRF loopback auto provision V6 previous")
    PER_VRF_LOOPBACK_IP_RANGE: Optional[str] = Field(None, description="Per VRF loopback IP range")
    PER_VRF_LOOPBACK_IP_RANGE_V6: Optional[str] = Field(None, description="Per VRF loopback IP range V6")
    PFC_WATCH_INT: Optional[str] = Field(None, description="PFC watch interval")
    PFC_WATCH_INT_PREV: Optional[str] = Field(None, description="PFC watch interval previous")
    PHANTOM_RP_LB_ID1: Optional[str] = Field(None, description="Phantom RP LB ID1")
    PHANTOM_RP_LB_ID2: Optional[str] = Field(None, description="Phantom RP LB ID2")
    PHANTOM_RP_LB_ID3: Optional[str] = Field(None, description="Phantom RP LB ID3")
    PHANTOM_RP_LB_ID4: Optional[str] = Field(None, description="Phantom RP LB ID4")
    PIM_HELLO_AUTH_ENABLE: Optional[str] = Field(None, description="PIM hello authentication enable")
    PIM_HELLO_AUTH_KEY: Optional[str] = Field(None, description="PIM hello authentication key")
    PM_ENABLE: Optional[str] = Field(None, description="PM enable")
    PM_ENABLE_PREV: Optional[str] = Field(None, description="PM enable previous")
    PNP_ENABLE_INTERNAL: Optional[str] = Field(None, description="PNP enable internal")
    POWER_REDUNDANCY_MODE: Optional[str] = Field(None, description="Power redundancy mode")
    PREMSO_PARENT_FABRIC: Optional[str] = Field(None, description="Pre-MSO parent fabric")
    PTP_DOMAIN_ID: Optional[str] = Field(None, description="PTP domain ID")
    PTP_LB_ID: Optional[str] = Field(None, description="PTP LB ID")
    PTP_VLAN_ID: Optional[str] = Field(None, description="PTP VLAN ID")
    QKD_PROFILE_NAME: Optional[str] = Field(None, description="QKD profile name")
    QKD_PROFILE_NAME_PREV: Optional[str] = Field(None, description="QKD profile name previous")
    REPLICATION_MODE: Optional[str] = Field(None, description="Replication mode")
    ROUTER_ID_RANGE: Optional[str] = Field(None, description="Router ID range")
    ROUTE_MAP_SEQUENCE_NUMBER_RANGE: Optional[str] = Field(None, description="Route map sequence number range")
    RP_COUNT: Optional[str] = Field(None, description="RP count")
    RP_LB_ID: Optional[str] = Field(None, description="RP LB ID")
    RP_MODE: Optional[str] = Field(None, description="RP mode")
    RR_COUNT: Optional[str] = Field(None, description="RR count")
    SEED_SWITCH_CORE_INTERFACES: Optional[str] = Field(None, description="Seed switch core interfaces")
    SERVICE_NETWORK_VLAN_RANGE: Optional[str] = Field(None, description="Service network VLAN range")
    SGT_ID_RANGE: Optional[str] = Field(None, description="SGT ID range")
    SGT_NAME_PREFIX: Optional[str] = Field(None, description="SGT name prefix")
    SGT_OPER_STATUS: Optional[str] = Field(None, description="SGT operational status")
    SGT_PREPROVISION: Optional[str] = Field(None, description="SGT pre-provision")
    SGT_PREPROVISION_PREV: Optional[str] = Field(None, description="SGT pre-provision previous")
    SGT_PREPROV_RECALC_STATUS: Optional[str] = Field(None, description="SGT pre-provision recalc status")
    SGT_RECALC_STATUS: Optional[str] = Field(None, description="SGT recalc status")
    SITE_ID: Optional[str] = Field(None, description="Site ID")
    SITE_ID_POLICY_ID: Optional[str] = Field(None, description="Site ID policy ID")
    SLA_ID_RANGE: Optional[str] = Field(None, description="SLA ID range")
    SNMP_SERVER_HOST_TRAP: Optional[str] = Field(None, description="SNMP server host trap")
    SPINE_COUNT: Optional[str] = Field(None, description="Spine count")
    SPINE_SWITCH_CORE_INTERFACES: Optional[str] = Field(None, description="Spine switch core interfaces")
    SSPINE_ADD_DEL_DEBUG_FLAG: Optional[str] = Field(None, description="Super spine add/del debug flag")
    SSPINE_COUNT: Optional[str] = Field(None, description="Super spine count")
    STATIC_UNDERLAY_IP_ALLOC: Optional[str] = Field(None, description="Static underlay IP allocation")
    STP_BRIDGE_PRIORITY: Optional[str] = Field(None, description="STP bridge priority")
    STP_ROOT_OPTION: Optional[str] = Field(None, description="STP root option")
    STP_VLAN_RANGE: Optional[str] = Field(None, description="STP VLAN range")
    STRICT_CC_MODE: Optional[str] = Field(None, description="Strict CC mode")
    SUBINTERFACE_RANGE: Optional[str] = Field(None, description="Subinterface range")
    SUBNET_RANGE: Optional[str] = Field(None, description="Subnet range")
    SUBNET_TARGET_MASK: Optional[str] = Field(None, description="Subnet target mask")
    SYSLOG_SERVER_IP_LIST: Optional[str] = Field(None, description="Syslog server IP list")
    SYSLOG_SERVER_VRF: Optional[str] = Field(None, description="Syslog server VRF")
    SYSLOG_SEV: Optional[str] = Field(None, description="Syslog severity")
    TCAM_ALLOCATION: Optional[str] = Field(None, description="TCAM allocation")
    TOPDOWN_CONFIG_RM_TRACKING: Optional[str] = Field(None, description="Top-down config RM tracking")
    TRUSTPOINT_LABEL: Optional[str] = Field(None, description="Trustpoint label")
    UNDERLAY_IS_V6: Optional[str] = Field(None, description="Underlay is V6")
    UNDERLAY_IS_V6_PREV: Optional[str] = Field(None, description="Underlay is V6 previous")
    UNNUM_BOOTSTRAP_LB_ID: Optional[str] = Field(None, description="Unnumbered bootstrap LB ID")
    UNNUM_DHCP_END: Optional[str] = Field(None, description="Unnumbered DHCP end")
    UNNUM_DHCP_END_INTERNAL: Optional[str] = Field(None, description="Unnumbered DHCP end internal")
    UNNUM_DHCP_START: Optional[str] = Field(None, description="Unnumbered DHCP start")
    UNNUM_DHCP_START_INTERNAL: Optional[str] = Field(None, description="Unnumbered DHCP start internal")
    UPGRADE_FROM_VERSION: Optional[str] = Field(None, description="Upgrade from version")
    USE_LINK_LOCAL: Optional[str] = Field(None, description="Use link local")
    V6_SUBNET_RANGE: Optional[str] = Field(None, description="V6 subnet range")
    V6_SUBNET_TARGET_MASK: Optional[str] = Field(None, description="V6 subnet target mask")
    VPC_AUTO_RECOVERY_TIME: Optional[str] = Field(None, description="VPC auto recovery time")
    VPC_DELAY_RESTORE: Optional[str] = Field(None, description="VPC delay restore")
    VPC_DELAY_RESTORE_TIME: Optional[str] = Field(None, description="VPC delay restore time")
    VPC_DOMAIN_ID_RANGE: Optional[str] = Field(None, description="VPC domain ID range")
    VPC_ENABLE_IPv6_ND_SYNC: Optional[str] = Field(None, description="VPC enable IPv6 ND sync")
    VPC_PEER_KEEP_ALIVE_OPTION: Optional[str] = Field(None, description="VPC peer keep alive option")
    VPC_PEER_LINK_PO: Optional[str] = Field(None, description="VPC peer link PO")
    VPC_PEER_LINK_VLAN: Optional[str] = Field(None, description="VPC peer link VLAN")
    VRF_LITE_AUTOCONFIG: Optional[str] = Field(None, description="VRF lite auto-config")
    VRF_VLAN_RANGE: Optional[str] = Field(None, description="VRF VLAN range")
    abstract_anycast_rp: Optional[str] = Field(None, description="Abstract anycast RP")
    abstract_bgp: Optional[str] = Field(None, description="Abstract BGP")
    abstract_bgp_neighbor: Optional[str] = Field(None, description="Abstract BGP neighbor")
    abstract_bgp_rr: Optional[str] = Field(None, description="Abstract BGP RR")
    abstract_dhcp: Optional[str] = Field(None, description="Abstract DHCP")
    abstract_extra_config_bootstrap: Optional[str] = Field(None, description="Abstract extra config bootstrap")
    abstract_extra_config_leaf: Optional[str] = Field(None, description="Abstract extra config leaf")
    abstract_extra_config_spine: Optional[str] = Field(None, description="Abstract extra config spine")
    abstract_extra_config_tor: Optional[str] = Field(None, description="Abstract extra config ToR")
    abstract_feature_leaf: Optional[str] = Field(None, description="Abstract feature leaf")
    abstract_feature_spine: Optional[str] = Field(None, description="Abstract feature spine")
    abstract_isis: Optional[str] = Field(None, description="Abstract ISIS")
    abstract_isis_interface: Optional[str] = Field(None, description="Abstract ISIS interface")
    abstract_loopback_interface: Optional[str] = Field(None, description="Abstract loopback interface")
    abstract_multicast: Optional[str] = Field(None, description="Abstract multicast")
    abstract_ospf: Optional[str] = Field(None, description="Abstract OSPF")
    abstract_ospf_interface: Optional[str] = Field(None, description="Abstract OSPF interface")
    abstract_pim_interface: Optional[str] = Field(None, description="Abstract PIM interface")
    abstract_route_map: Optional[str] = Field(None, description="Abstract route map")
    abstract_routed_host: Optional[str] = Field(None, description="Abstract routed host")
    abstract_trunk_host: Optional[str] = Field(None, description="Abstract trunk host")
    abstract_vlan_interface: Optional[str] = Field(None, description="Abstract VLAN interface")
    abstract_vpc_domain: Optional[str] = Field(None, description="Abstract VPC domain")
    dcnmUser: Optional[str] = Field(None, description="DCNM user")
    default_network: Optional[str] = Field(None, description="Default network")
    default_pvlan_sec_network: Optional[str] = Field(None, description="Default PVLAN secondary network")
    default_vrf: Optional[str] = Field(None, description="Default VRF")
    enableRealTimeBackup: Optional[str] = Field(None, description="Enable real-time backup")
    enableScheduledBackup: Optional[str] = Field(None, description="Enable scheduled backup")
    network_extension_template: Optional[str] = Field(None, description="Network extension template")
    scheduledTime: Optional[str] = Field(None, description="Scheduled time")
    temp_anycast_gateway: Optional[str] = Field(None, description="Temp anycast gateway")
    temp_vpc_domain_mgmt: Optional[str] = Field(None, description="Temp VPC domain management")
    temp_vpc_peer_link: Optional[str] = Field(None, description="Temp VPC peer link")
    vrf_extension_template: Optional[str] = Field(None, description="VRF extension template")


class ControllerResponseFabricsEasyFabricGet(BaseModel):
    """
    Model representing the controller response for the following endpoint:

    - Verb: GET
    - Path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{fabricName}

    # Raises

    ValueError if validation fails
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
    )

    asn: str = Field(..., min_length=1, description="ASN number")
    createdOn: int = Field(..., description="Creation timestamp")
    deviceType: str = Field(..., description="Device type")
    fabricId: str = Field(..., description="Fabric ID")
    fabricName: str = Field(..., description="Fabric name")
    fabricTechnology: str = Field(..., description="Fabric technology")
    fabricTechnologyFriendly: str = Field(..., description="Fabric technology friendly name")
    fabricType: str = Field(..., description="Fabric type")
    fabricTypeFriendly: str = Field(..., description="Fabric type friendly name")
    id: int = Field(..., description="Fabric ID")
    modifiedOn: int = Field(..., description="Modification timestamp")
    networkExtensionTemplate: str = Field(default="Default_Network_Extension_Universal", description="Network extension template")
    networkTemplate: str = Field(default="Default_Network_Universal", description="Network template")
    nvPairs: ControllerResponseFabricsEasyFabricGetNvPairs = Field(..., description="NVPairs configuration")
    operStatus: str = Field(..., description="Operational status")
    provisionMode: str = Field(..., description="Provisioning mode")
    replicationMode: str = Field(..., description="Replication mode")
    siteId: str = Field(..., description="Site ID")
    templateFabricType: str = Field(..., description="Template fabric type")
    templateName: str = Field(..., min_length=1, description="Template name")
    vrfExtensionTemplate: str = Field(default="Default_VRF_Extension_Universal", min_length=1, description="VRF extension template")
    vrfTemplate: str = Field(default="Default_VRF_Universal", min_length=1, description="VRF template")
