---
namespace: cisco
name: dcnm
version: 0.9.0-dev1
readme: README.md
authors:
  - Shrishail Kariyappanavar <nkshrishail>
  - Mallik Mudigonda <mmudigon>
  - Karthik Babu Harichandra Babu <kharicha>
  - Mike Wiebe <mikewiebe>
description: Ansible collection for the Cisco Data Center Nework Manager (DCNM)
license_file: LICENSE 
tags: [cisco, dcnm, nxos, networking, vxlan]
dependencies:
  "ansible.netcommon": "*"
repository: https://github.com/CiscoDevNet/ansible-dcnm
