---
namespace: cisco
name: dcnm
version: 3.7.0
readme: README.md
authors:
  - Shrishail Kariyappanavar <nkshrishail>
  - Mallik Mudigonda <mmudigon>
  - Karthik Babu Harichandra Babu <kharicha>
  - Mike Wiebe <mikewiebe>
  - Praveen Ramoorthy <praveenramoorthy>
  - Allen Robel <allenrobel>
  - Shangxin Du <dsx1123>
description: Ansible collection for the Cisco Nexus® Dashboard Fabric Controller (NDFC) - formerly DCNM
license: Apache-2.0
tags: [cisco, ndfc, dcnm, nxos, networking, vxlan]
dependencies:
  "ansible.netcommon": ">=2.6.1"
repository: https://github.com/CiscoDevNet/ansible-dcnm
