---
# This playbook can be used to execute the dcnm_fabric test role.
#
# Replace the vars: section with details for your 2 spine, 4 leaf fabric.
#
#
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # This testcase field can run any test in the tests directory for the role
    # testcase: dcnm_fabric_deleted_basic
    testcase: dcnm_fabric_merged_basic
    # testcase: dcnm_fabric_merged_save_deploy
    # testcase: dcnm_fabric_merged_basic_ipfm
    # testcase: dcnm_fabric_replaced_basic
    # testcase: dcnm_fabric_replaced_save_deploy
    fabric_name_1: VXLAN_EVPN_Fabric
    fabric_type_1: VXLAN_EVPN
    fabric_name_2: VXLAN_EVPN_MSD_Fabric
    fabric_type_2: VXLAN_EVPN_MSD
    fabric_name_3: LAN_CLASSIC_Fabric
    fabric_type_3: LAN_CLASSIC
    fabric_name_4: IPFM_Fabric
    fabric_type_4: IPFM

  roles:
    - dcnm_fabric
