---
# This playbook can be used to execute the dcnm_fabric test role.
#
# Replace the vars: section with details for your 2 spine, 4 leaf fabric.
#
#
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # This testcase field can run any test in the tests directory for the role
    testcase: spine_leaf_basic
    fabric_name: fabric-name
    spine1: n9k-spine1.example.com
    spine2: n9k-spine2.example.com
    leaf1: n9k-leaf1.example.com
    leaf2: n9k-leaf2.example.com
    leaf3: n9k-leaf3.example.com
    leaf4: n9k-leaf4.example.com
    username: admin
    password: "secret-password"

  roles:
    - dcnm_fabric

# Uncomment the following play if you want to verify connectivity between
# host a and host c and d across the vxlan fabric setup by test spine_leaf_basic
#

# - hosts: nxos
#   gather_facts: no
#   connection: ansible.netcommon.network_cli
#
#   tasks:
#     - name: Verify IP reachability for vni 4000
#       nxos_ping:
#         dest: 192.168.1.20
#         state: present
#
#     - name: Verify IP reachability for vni 7000
#       nxos_ping:
#         dest: 192.168.2.20
#         state: present
