---
# This playbook can be used to execute the dcnm_fabric test role.
#
# Modify the vars section with details for testing setup.
#
# NOTES:
# 1. For the IPFM test cases (dcnm_*_ipfm), ensure that the controller
#    is running in IPFM mode.  i.e. Ensure that 
#    Fabric Controller -> Admin -> System Settings -> Feature Management
#    "IP Fabric for Media" is checked.
# 2. For all other test cases, ensure that
#    Fabric Controller -> Admin -> System Settings -> Feature Management
#    "Fabric Builder" is checked.
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # This testcase field can run any test in the tests directory for the role
    # testcase: dcnm_fabric_deleted_basic
    # testcase: dcnm_fabric_merged_basic
    # testcase: dcnm_fabric_merged_save_deploy
    # testcase: dcnm_fabric_replaced_basic
    # testcase: dcnm_fabric_replaced_save_deploy
    # testcase: dcnm_fabric_merged_basic_ipfm
    testcase: dcnm_fabric_merged_save_deploy_ipfm
    fabric_name_1: VXLAN_EVPN_Fabric
    fabric_type_1: VXLAN_EVPN
    fabric_name_2: VXLAN_EVPN_MSD_Fabric
    fabric_type_2: VXLAN_EVPN_MSD
    fabric_name_3: LAN_CLASSIC_Fabric
    fabric_type_3: LAN_CLASSIC
    fabric_name_4: IPFM_Fabric
    fabric_type_4: IPFM
    leaf_1: 172.22.150.103
    leaf_2: 172.22.150.104

  roles:
    - dcnm_fabric
