---
# This playbook can be used to execute integration tests for
# the roles located in:
#
# ./tests/integration/targets/dcnm_fabric/tests/*.yaml
#
# Modify the vars section with details for your testing setup.
#
# NOTES:
# 1. For the IPFM test cases (dcnm_*_ipfm), ensure that the controller
#    is running in IPFM mode.  i.e. Ensure that 
#    Fabric Controller -> Admin -> System Settings -> Feature Management
#    "IP Fabric for Media" is checked.
# 2. For all other test cases, ensure that
#    Fabric Controller -> Admin -> System Settings -> Feature Management
#    "Fabric Builder" is checked.
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # Uncomment ONE of the following testcases
    # testcase: dcnm_fabric_deleted_basic
    # testcase: dcnm_fabric_deleted_basic_ipfm
    # testcase: dcnm_fabric_deleted_basic_isn
    # testcase: dcnm_fabric_deleted_basic_lan_classic
    # testcase: dcnm_fabric_deleted_basic_msd
    # testcase: dcnm_fabric_deleted_basic_vxlan
    # testcase: dcnm_fabric_merged_basic
    # testcase: dcnm_fabric_merged_basic_ipfm
    # testcase: dcnm_fabric_merged_basic_isn
    # testcase: dcnm_fabric_merged_save_deploy
    # testcase: dcnm_fabric_merged_save_deploy_ipfm
    # testcase: dcnm_fabric_replaced_basic
    # testcase: dcnm_fabric_replaced_basic_ipfm
    # testcase: dcnm_fabric_replaced_basic_isn
    # testcase: dcnm_fabric_replaced_basic_vxlan
    # testcase: dcnm_fabric_replaced_basic_vxlan_site_id
    # testcase: dcnm_fabric_replaced_save_deploy
    # testcase: dcnm_fabric_replaced_save_deploy_ipfm
    # testcase: dcnm_fabric_query_basic.yaml
    fabric_name_00: VXLAN_EVPN
    fabric_type_00: VXLAN_EVPN
    fabric_name_10: LAN_CLASSIC
    fabric_type_10: LAN_CLASSIC
    fabric_name_20: BGP
    fabric_type_20: BGP
    fabric_name_30: ISN
    fabric_type_30: ISN
    fabric_name_40: IPFM
    fabric_type_40: IPFM
    fabric_name_50: AI
    fabric_type_50: AI
    fabric_name_100: MSD
    fabric_type_100: VXLAN_EVPN_MSD
    fabric_name_110: MCFG
    fabric_type_110: MCFG
    fabric_name_120: FG
    fabric_type_120: FG
    leaf_1: 172.22.150.103
    leaf_2: 172.22.150.104
    nxos_username: admin
    nxos_password: myNxosPassword

  roles:
    - dcnm_fabric
