---
# This playbook can be used to execute integration tests for
# the roles located in:
#
# ./tests/integration/targets/dcnm_fabric/tests/*.yaml
#
# Modify the vars section with details for your testing setup.
#
# NOTES:
# 1. For the IPFM test cases (dcnm_*_ipfm), ensure that the controller
#    is running in IPFM mode.  i.e. Ensure that 
#    Fabric Controller -> Admin -> System Settings -> Feature Management
#    "IP Fabric for Media" is checked.
# 2. For all other test cases, ensure that
#    Fabric Controller -> Admin -> System Settings -> Feature Management
#    "Fabric Builder" is checked.
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # Uncomment ONE of the following testcases
    # testcase: dcnm_fabric_deleted_basic
    # testcase: dcnm_fabric_deleted_basic_ipfm
    # testcase: dcnm_fabric_deleted_basic_lan_classic
    # testcase: dcnm_fabric_deleted_basic_msd
    # testcase: dcnm_fabric_deleted_basic_vxlan
    # testcase: dcnm_fabric_merged_basic
    # testcase: dcnm_fabric_merged_basic_ipfm
    # testcase: dcnm_fabric_merged_save_deploy
    # testcase: dcnm_fabric_merged_save_deploy_ipfm
    # testcase: dcnm_fabric_replaced_basic
    # testcase: dcnm_fabric_replaced_basic_vxlan
    # testcase: dcnm_fabric_replaced_basic_vxlan_site_id
    # testcase: dcnm_fabric_replaced_basic_ipfm
    # testcase: dcnm_fabric_replaced_save_deploy
    # testcase: dcnm_fabric_replaced_save_deploy_ipfm
    # testcase: dcnm_fabric_query_basic.yaml
    fabric_name_1: VXLAN_EVPN_Fabric
    fabric_type_1: VXLAN_EVPN
    fabric_name_2: VXLAN_EVPN_MSD_Fabric
    fabric_type_2: VXLAN_EVPN_MSD
    fabric_name_3: LAN_CLASSIC_Fabric
    fabric_type_3: LAN_CLASSIC
    fabric_name_4: IPFM_Fabric
    fabric_type_4: IPFM
    leaf_1: 172.22.150.103
    leaf_2: 172.22.150.104
    nxos_username: admin
    nxos_password: myNxosPassword

  roles:
    - dcnm_fabric
