all:
  vars:
    ansible_user: "admin"
    ansible_password: "password-secret"
    ansible_python_interpreter: python
    ansible_httpapi_validate_certs: False
    ansible_httpapi_use_ssl: True
  children:
    dcnm:
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: cisco.dcnm.dcnm
      hosts:
        dcnm-instance.example.com:
    nxos:
      hosts:
        n9k-hosta.example.com:
           ansible_connection: ansible.netcommon.network_cli
           ansible_network_os: cisco.nxos.nxos
           ansible_ssh_port: 22
