# GENERATED - DO NOT EDIT. Static interface binding table.
# Generator: tools/gie_generate_binding_table.py, from the approved registry YAML.
# Runtime imports this module only; it never reads YAML or NDFC templates.
# provenance_sha256 = 4151cd21632dafa00d62bc460da04022e98aa5f8fab81a05ea2e2a133c0177e7

from __future__ import absolute_import, division, print_function
__metaclass__ = type

PROVENANCE_SHA256 = "4151cd21632dafa00d62bc460da04022e98aa5f8fab81a05ea2e2a133c0177e7"

BINDING_TABLE = (
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'FLOWCONTROL_RECEIVE',
        'profile_key': 'flowcontrol_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'FLOWCONTROL_SEND',
        'profile_key': 'flowcontrol_send',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'DISABLE_EIGRP_BFD',
        'profile_key': 'disable_eigrp_bfd',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'EIGRP_IPV4_PASSIVE',
        'profile_key': 'eigrp_ipv4_passive',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'EIGRP_NO_IPV4_PASSIVE',
        'profile_key': 'eigrp_no_ipv4_passive',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'EIGRP_NO_IPV6_PASSIVE',
        'profile_key': 'eigrp_no_ipv6_passive',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'EIGRP_PROCESS_TAG',
        'profile_key': 'eigrp_process_tag',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'ENABLE_EIGRP_BFD',
        'profile_key': 'enable_eigrp_bfd',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'ENABLE_EIGRP_ROUTING',
        'profile_key': 'enable_eigrp_routing',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'ENABLE_EIGRP_SHUTDOWN',
        'profile_key': 'enable_eigrp_shutdown',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'ENABLE_OSPF',
        'profile_key': 'enable_ospf',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'ENABLE_OSPF_AUTH',
        'profile_key': 'enable_ospf_auth',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'ENABLE_PIM_SPARSE',
        'profile_key': 'enable_pim_sparse',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_ADVERTISE_SUBNET',
        'profile_key': 'ospf_advertise_subnet',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_AREA_ID',
        'profile_key': 'ospf_area_id',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'string',
        'default_template': '0.0.0.0',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 15,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY',
        'profile_key': 'ospf_authentication_key',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY_TYPE',
        'profile_key': 'ospf_authentication_key_type',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'enum',
        'valid_values': ('0', '3', '7'),
        'default_template': '3',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_AUTH_KEY',
        'profile_key': 'ospf_auth_key',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_AUTH_KEY_ID',
        'profile_key': 'ospf_auth_key_id',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'integer',
        'default_template': 1,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_BFD',
        'profile_key': 'ospf_bfd',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_COST',
        'profile_key': 'ospf_cost',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_DEAD_INTERVAL',
        'profile_key': 'ospf_dead_interval',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_HELLO_INTERVAL',
        'profile_key': 'ospf_hello_interval',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_MTU_IGNORE',
        'profile_key': 'ospf_mtu_ignore',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_NETWORK_TYPE',
        'profile_key': 'ospf_network_type',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'enum',
        'valid_values': ('no_change', 'broadcast', 'point_to_point'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_PRIORITY',
        'profile_key': 'ospf_priority',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_RETRANSMIT_INTERVAL',
        'profile_key': 'ospf_retransmit_interval',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_SHUTDOWN',
        'profile_key': 'ospf_shutdown',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_TAG',
        'profile_key': 'ospf_tag',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_loopback',
        'parent_nvpair': 'OSPF_TRANSMIT_DELAY',
        'profile_key': 'ospf_transmit_delay',
        'applicable_interface_type': 'lo',
        'applicable_mode': 'lo',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 450,
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'ENABLE_VPC_PEER_LINK',
        'profile_key': 'enable_vpc_peer_link',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'GUARD_MODE',
        'profile_key': 'guard_mode',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('root', 'none', 'loop', 'no'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ARP_TIMEOUT',
        'profile_key': 'arp_timeout',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 60,
        'max_value': 28800,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DAMPENING_HALF_LIFE',
        'profile_key': 'dampening_half_life',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 30,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DAMPENING_MAX_SUPPRESS',
        'profile_key': 'dampening_max_suppress',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DAMPENING_RESTART',
        'profile_key': 'dampening_restart',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DAMPENING_RESTART_PENALTY',
        'profile_key': 'dampening_restart_penalty',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 20000,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DAMPENING_REUSE',
        'profile_key': 'dampening_reuse',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 20000,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DAMPENING_SUPPRESS',
        'profile_key': 'dampening_suppress',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 20000,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_BFD_ECHO',
        'profile_key': 'disable_bfd_echo',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_EIGRP_BFD',
        'profile_key': 'disable_eigrp_bfd',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_IPV4_REDIRECTS',
        'profile_key': 'disable_ipv4_redirects',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_IPV6_REDIRECTS',
        'profile_key': 'disable_ipv6_redirects',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_IPV4_DISTRIBUTE_LIST_DIRECTION',
        'profile_key': 'eigrp_ipv4_distribute_list_direction',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('in', 'out'),
        'default_template': 'out',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_IPV4_DISTRIBUTE_LIST_PREFIX_LIST',
        'profile_key': 'eigrp_ipv4_distribute_list_prefix_list',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 63,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_IPV4_PASSIVE',
        'profile_key': 'eigrp_ipv4_passive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_IPV6_DISTRIBUTE_LIST_DIRECTION',
        'profile_key': 'eigrp_ipv6_distribute_list_direction',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('in', 'out'),
        'default_template': 'out',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_IPV6_DISTRIBUTE_LIST_PREFIX_LIST',
        'profile_key': 'eigrp_ipv6_distribute_list_prefix_list',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 63,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_NO_IPV4_PASSIVE',
        'profile_key': 'eigrp_no_ipv4_passive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_NO_IPV6_PASSIVE',
        'profile_key': 'eigrp_no_ipv6_passive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'EIGRP_PROCESS_TAG',
        'profile_key': 'eigrp_process_tag',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_DAMPENING',
        'profile_key': 'enable_dampening',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_EIGRP_BFD',
        'profile_key': 'enable_eigrp_bfd',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_EIGRP_IPV6_ROUTING',
        'profile_key': 'enable_eigrp_ipv6_routing',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_EIGRP_ROUTING',
        'profile_key': 'enable_eigrp_routing',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_EIGRP_SHUTDOWN',
        'profile_key': 'enable_eigrp_shutdown',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_MACSEC_INTERFACE_POLICY',
        'profile_key': 'enable_macsec_interface_policy',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_OSPF',
        'profile_key': 'enable_ospf',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_OSPF_AUTH',
        'profile_key': 'enable_ospf_auth',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_PIM_BFD_INSTANCE',
        'profile_key': 'enable_pim_bfd_instance',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_PIM_SPARSE',
        'profile_key': 'enable_pim_sparse',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'IPV4_ACL_IN',
        'profile_key': 'ipv4_acl_in',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'IPV6_ND_SUPPRESS_RA',
        'profile_key': 'ipv6_nd_suppress_ra',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'IPv6_LINK_LOCAL',
        'profile_key': 'ipv6_link_local',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 45,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'MACSEC_FALLBACK_KEY_CHAIN_NAME',
        'profile_key': 'macsec_fallback_key_chain_name',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'MACSEC_KEY_CHAIN_NAME',
        'profile_key': 'macsec_key_chain_name',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'MACSEC_POLICY_NAME',
        'profile_key': 'macsec_policy_name',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_AREA_ID',
        'profile_key': 'ospf_area_id',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'default_template': '0.0.0.0',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 15,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY',
        'profile_key': 'ospf_authentication_key',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY_TYPE',
        'profile_key': 'ospf_authentication_key_type',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('0', '3', '7'),
        'default_template': '3',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_AUTH_KEY',
        'profile_key': 'ospf_auth_key',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_AUTH_KEY_ID',
        'profile_key': 'ospf_auth_key_id',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'default_template': 1,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_BFD_MODE',
        'profile_key': 'ospf_bfd_mode',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('no_change', 'enable', 'disable'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_COST',
        'profile_key': 'ospf_cost',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_DEAD_INTERVAL',
        'profile_key': 'ospf_dead_interval',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_HELLO_INTERVAL',
        'profile_key': 'ospf_hello_interval',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_MTU_IGNORE',
        'profile_key': 'ospf_mtu_ignore',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_NETWORK_TYPE',
        'profile_key': 'ospf_network_type',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('no_change', 'broadcast', 'point_to_point'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_PASSIVE_MODE',
        'profile_key': 'ospf_passive_mode',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('no_change', 'passive', 'no_passive'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_PRIORITY',
        'profile_key': 'ospf_priority',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_SHUTDOWN',
        'profile_key': 'ospf_shutdown',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_TAG',
        'profile_key': 'ospf_tag',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_TRANSMIT_DELAY',
        'profile_key': 'ospf_transmit_delay',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 450,
        'no_log': False,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'PIM_DR_PRIORITY',
        'profile_key': 'pim_dr_priority',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'default_template': 1,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 4294967295,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ARP_TIMEOUT',
        'profile_key': 'arp_timeout',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 60,
        'max_value': 28800,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'BFD_MIN_RX_INTERVAL',
        'profile_key': 'bfd_min_rx_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 50,
        'max_value': 999,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'BFD_MULTIPLIER',
        'profile_key': 'bfd_multiplier',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 50,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'BFD_TX_INTERVAL',
        'profile_key': 'bfd_tx_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 50,
        'max_value': 999,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'DISABLE_EIGRP_BFD',
        'profile_key': 'disable_eigrp_bfd',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'DISABLE_IPV4_REDIRECTS',
        'profile_key': 'disable_ipv4_redirects',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'DISABLE_IPV6_REDIRECTS',
        'profile_key': 'disable_ipv6_redirects',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_IPV4_DISTRIBUTE_LIST_DIRECTION',
        'profile_key': 'eigrp_ipv4_distribute_list_direction',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'enum',
        'valid_values': ('in', 'out'),
        'default_template': 'out',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_IPV4_DISTRIBUTE_LIST_PREFIX_LIST',
        'profile_key': 'eigrp_ipv4_distribute_list_prefix_list',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 63,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_IPV4_PASSIVE',
        'profile_key': 'eigrp_ipv4_passive',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_IPV6_DISTRIBUTE_LIST_DIRECTION',
        'profile_key': 'eigrp_ipv6_distribute_list_direction',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'enum',
        'valid_values': ('in', 'out'),
        'default_template': 'out',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_IPV6_DISTRIBUTE_LIST_PREFIX_LIST',
        'profile_key': 'eigrp_ipv6_distribute_list_prefix_list',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 63,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_NO_IPV4_PASSIVE',
        'profile_key': 'eigrp_no_ipv4_passive',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_NO_IPV6_PASSIVE',
        'profile_key': 'eigrp_no_ipv6_passive',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'EIGRP_PROCESS_TAG',
        'profile_key': 'eigrp_process_tag',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_BFD_INTERVAL',
        'profile_key': 'enable_bfd_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_EIGRP_BFD',
        'profile_key': 'enable_eigrp_bfd',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_EIGRP_IPV6_ROUTING',
        'profile_key': 'enable_eigrp_ipv6_routing',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_EIGRP_ROUTING',
        'profile_key': 'enable_eigrp_routing',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_EIGRP_SHUTDOWN',
        'profile_key': 'enable_eigrp_shutdown',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_OSPF',
        'profile_key': 'enable_ospf',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_OSPF_AUTH',
        'profile_key': 'enable_ospf_auth',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_PIM_SPARSE',
        'profile_key': 'enable_pim_sparse',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'IPV6_ND_SUPPRESS_RA',
        'profile_key': 'ipv6_nd_suppress_ra',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'IPv6_LINK_LOCAL',
        'profile_key': 'ipv6_link_local',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 45,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_AREA_ID',
        'profile_key': 'ospf_area_id',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'default_template': '0.0.0.0',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 15,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY',
        'profile_key': 'ospf_authentication_key',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY_TYPE',
        'profile_key': 'ospf_authentication_key_type',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'enum',
        'valid_values': ('0', '3', '7'),
        'default_template': '3',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_AUTH_KEY',
        'profile_key': 'ospf_auth_key',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_AUTH_KEY_ID',
        'profile_key': 'ospf_auth_key_id',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'default_template': 1,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_BFD',
        'profile_key': 'ospf_bfd',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_COST',
        'profile_key': 'ospf_cost',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_DEAD_INTERVAL',
        'profile_key': 'ospf_dead_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_HELLO_INTERVAL',
        'profile_key': 'ospf_hello_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_MTU_IGNORE',
        'profile_key': 'ospf_mtu_ignore',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_NETWORK_TYPE',
        'profile_key': 'ospf_network_type',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'enum',
        'valid_values': ('no_change', 'broadcast', 'point_to_point'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_PASSIVE_INTERFACE',
        'profile_key': 'ospf_passive_interface',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_PRIORITY',
        'profile_key': 'ospf_priority',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_RETRANSMIT_INTERVAL',
        'profile_key': 'ospf_retransmit_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_SHUTDOWN',
        'profile_key': 'ospf_shutdown',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_TAG',
        'profile_key': 'ospf_tag',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_TRANSMIT_DELAY',
        'profile_key': 'ospf_transmit_delay',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 450,
        'no_log': False,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'PIM_DR_PRIORITY',
        'profile_key': 'pim_dr_priority',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'default_template': 1,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 4294967295,
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'FLOWCONTROL_RECEIVE',
        'profile_key': 'flowcontrol_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'FLOWCONTROL_SEND',
        'profile_key': 'flowcontrol_send',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'GUARD_MODE',
        'profile_key': 'guard_mode',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('root', 'none', 'loop', 'no'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ARP_TIMEOUT',
        'profile_key': 'arp_timeout',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 60,
        'max_value': 28800,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'BFD_MIN_RX_INTERVAL',
        'profile_key': 'bfd_min_rx_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 50,
        'max_value': 999,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'BFD_MULTIPLIER',
        'profile_key': 'bfd_multiplier',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 50,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'BFD_TX_INTERVAL',
        'profile_key': 'bfd_tx_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 50,
        'max_value': 999,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'DISABLE_BFD_ECHO',
        'profile_key': 'disable_bfd_echo',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'DISABLE_EIGRP_BFD',
        'profile_key': 'disable_eigrp_bfd',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'DISABLE_IPV4_REDIRECTS',
        'profile_key': 'disable_ipv4_redirects',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'DISABLE_IPV6_REDIRECTS',
        'profile_key': 'disable_ipv6_redirects',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_IPV4_DISTRIBUTE_LIST_DIRECTION',
        'profile_key': 'eigrp_ipv4_distribute_list_direction',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('in', 'out'),
        'default_template': 'out',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_IPV4_DISTRIBUTE_LIST_PREFIX_LIST',
        'profile_key': 'eigrp_ipv4_distribute_list_prefix_list',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 63,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_IPV4_PASSIVE',
        'profile_key': 'eigrp_ipv4_passive',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_IPV6_DISTRIBUTE_LIST_DIRECTION',
        'profile_key': 'eigrp_ipv6_distribute_list_direction',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('in', 'out'),
        'default_template': 'out',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_IPV6_DISTRIBUTE_LIST_PREFIX_LIST',
        'profile_key': 'eigrp_ipv6_distribute_list_prefix_list',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 63,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_NO_IPV4_PASSIVE',
        'profile_key': 'eigrp_no_ipv4_passive',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_NO_IPV6_PASSIVE',
        'profile_key': 'eigrp_no_ipv6_passive',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'EIGRP_PROCESS_TAG',
        'profile_key': 'eigrp_process_tag',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_BFD_INTERVAL',
        'profile_key': 'enable_bfd_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_EIGRP_BFD',
        'profile_key': 'enable_eigrp_bfd',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_EIGRP_IPV6_ROUTING',
        'profile_key': 'enable_eigrp_ipv6_routing',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_EIGRP_ROUTING',
        'profile_key': 'enable_eigrp_routing',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_EIGRP_SHUTDOWN',
        'profile_key': 'enable_eigrp_shutdown',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_OSPF',
        'profile_key': 'enable_ospf',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_OSPF_AUTH',
        'profile_key': 'enable_ospf_auth',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_PIM_SPARSE',
        'profile_key': 'enable_pim_sparse',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'HSRP_GROUPv6',
        'profile_key': 'hsrp_groupv6',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 4095,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'HSRP_PREEMPT_DELAY_MINIMUM',
        'profile_key': 'hsrp_preempt_delay_minimum',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 3600,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'HSRP_PRIORITY_FORWARDING_THRESHOLD_LOWER',
        'profile_key': 'hsrp_priority_forwarding_threshold_lower',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'HSRP_PRIORITY_FORWARDING_THRESHOLD_UPPER',
        'profile_key': 'hsrp_priority_forwarding_threshold_upper',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'HSRP_VIPv6',
        'profile_key': 'hsrp_vipv6',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 45,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'IPV4_ACL_IN',
        'profile_key': 'ipv4_acl_in',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'IPV6_ND_SUPPRESS_RA',
        'profile_key': 'ipv6_nd_suppress_ra',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'IPv6_LINK_LOCAL',
        'profile_key': 'ipv6_link_local',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'max_length': 45,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_AREA_ID',
        'profile_key': 'ospf_area_id',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'default_template': '0.0.0.0',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 15,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY',
        'profile_key': 'ospf_authentication_key',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_AUTHENTICATION_KEY_TYPE',
        'profile_key': 'ospf_authentication_key_type',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('0', '3', '7'),
        'default_template': '3',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_AUTH_KEY',
        'profile_key': 'ospf_auth_key',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': True,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_AUTH_KEY_ID',
        'profile_key': 'ospf_auth_key_id',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'default_template': 1,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_BFD_MODE',
        'profile_key': 'ospf_bfd_mode',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('no_change', 'enable', 'disable'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_COST',
        'profile_key': 'ospf_cost',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_DEAD_INTERVAL',
        'profile_key': 'ospf_dead_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_HELLO_INTERVAL',
        'profile_key': 'ospf_hello_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_MTU_IGNORE',
        'profile_key': 'ospf_mtu_ignore',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_NETWORK_TYPE',
        'profile_key': 'ospf_network_type',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('no_change', 'broadcast', 'point_to_point'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_PASSIVE_MODE',
        'profile_key': 'ospf_passive_mode',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('no_change', 'passive', 'no_passive'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_PRIORITY',
        'profile_key': 'ospf_priority',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_RETRANSMIT_INTERVAL',
        'profile_key': 'ospf_retransmit_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_SHUTDOWN',
        'profile_key': 'ospf_shutdown',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_TAG',
        'profile_key': 'ospf_tag',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 20,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_TRANSMIT_DELAY',
        'profile_key': 'ospf_transmit_delay',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 450,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'PIM_DR_PRIORITY',
        'profile_key': 'pim_dr_priority',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'default_template': 1,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 4294967295,
        'no_log': False,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'PRIVATE_VLAN_MAPPING',
        'profile_key': 'private_vlan_mapping',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'GUARD_MODE',
        'profile_key': 'guard_mode',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('root', 'none', 'loop', 'no'),
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'no_log': False,
    },
)


def registered_profile_keys(parent_template):
    """Public profile keys registered for a parent (thin: exact set, no name heuristic)."""
    return {b['profile_key'] for b in BINDING_TABLE if b['parent_template'] == parent_template}


def resolve_binding(parent_template, profile_key):
    """Exactly one binding for (parent_template, profile_key), or None."""
    hits = [b for b in BINDING_TABLE
            if b['parent_template'] == parent_template and b['profile_key'] == profile_key]
    return hits[0] if len(hits) == 1 else None


def resolve_by_nvpair(parent_template, parent_nvpair):
    hits = [b for b in BINDING_TABLE
            if b['parent_template'] == parent_template and b['parent_nvpair'] == parent_nvpair]
    return hits[0] if len(hits) == 1 else None
