# GENERATED - DO NOT EDIT. Static interface binding table.
# Generator: tools/gie_generate_binding_table.py, from the approved registry YAML.
# Runtime imports this module only; it never reads YAML or NDFC templates.
# provenance_sha256 = f181a27dee5021176b99afd8e5d4efe569ce935233ca1e533e3ca5f031ce963a

from __future__ import absolute_import, division, print_function
__metaclass__ = type

PROVENANCE_SHA256 = "f181a27dee5021176b99afd8e5d4efe569ce935233ca1e533e3ca5f031ce963a"

BINDING_TABLE = (
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'FLOWCONTROL_RECEIVE',
        'profile_key': 'flowcontrol_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'FLOWCONTROL_SEND',
        'profile_key': 'flowcontrol_send',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_access_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_access_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_dot1q_tunnel_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'dot1q',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'GUARD_MODE',
        'profile_key': 'guard_mode',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('root', 'none', 'loop', 'no'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_port_channel_trunk_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'pc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_BFD_ECHO',
        'profile_key': 'disable_bfd_echo',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'ENABLE_OSPF',
        'profile_key': 'enable_ospf',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'IPV4_ACL_IN',
        'profile_key': 'ipv4_acl_in',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_AREA_ID',
        'profile_key': 'ospf_area_id',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'default_template': '0.0.0.0',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 15,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_BFD_MODE',
        'profile_key': 'ospf_bfd_mode',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('no_change', 'enable', 'disable'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_COST',
        'profile_key': 'ospf_cost',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_DEAD_INTERVAL',
        'profile_key': 'ospf_dead_interval',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_HELLO_INTERVAL',
        'profile_key': 'ospf_hello_interval',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_MTU_IGNORE',
        'profile_key': 'ospf_mtu_ignore',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_NETWORK_TYPE',
        'profile_key': 'ospf_network_type',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('no_change', 'broadcast', 'point_to_point'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_PASSIVE_MODE',
        'profile_key': 'ospf_passive_mode',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'enum',
        'valid_values': ('no_change', 'passive', 'no_passive'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_PRIORITY',
        'profile_key': 'ospf_priority',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_SHUTDOWN',
        'profile_key': 'ospf_shutdown',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_TAG',
        'profile_key': 'ospf_tag',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 20,
    },
    {
        'parent_template': 'int_routed_host',
        'parent_nvpair': 'OSPF_TRANSMIT_DELAY',
        'profile_key': 'ospf_transmit_delay',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'routed',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 450,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'ENABLE_OSPF',
        'profile_key': 'enable_ospf',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_AREA_ID',
        'profile_key': 'ospf_area_id',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'default_template': '0.0.0.0',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 15,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_BFD',
        'profile_key': 'ospf_bfd',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_COST',
        'profile_key': 'ospf_cost',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_DEAD_INTERVAL',
        'profile_key': 'ospf_dead_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_HELLO_INTERVAL',
        'profile_key': 'ospf_hello_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_MTU_IGNORE',
        'profile_key': 'ospf_mtu_ignore',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_NETWORK_TYPE',
        'profile_key': 'ospf_network_type',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'enum',
        'valid_values': ('no_change', 'broadcast', 'point_to_point'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_PASSIVE_INTERFACE',
        'profile_key': 'ospf_passive_interface',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_PRIORITY',
        'profile_key': 'ospf_priority',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_RETRANSMIT_INTERVAL',
        'profile_key': 'ospf_retransmit_interval',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_SHUTDOWN',
        'profile_key': 'ospf_shutdown',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_TAG',
        'profile_key': 'ospf_tag',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 20,
    },
    {
        'parent_template': 'int_subif',
        'parent_nvpair': 'OSPF_TRANSMIT_DELAY',
        'profile_key': 'ospf_transmit_delay',
        'applicable_interface_type': 'sub_int',
        'applicable_mode': 'subint',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 450,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'FLOWCONTROL_RECEIVE',
        'profile_key': 'flowcontrol_receive',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'FLOWCONTROL_SEND',
        'profile_key': 'flowcontrol_send',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('on', 'off'),
        'default_template': 'off',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'GUARD_MODE',
        'profile_key': 'guard_mode',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('root', 'none', 'loop', 'no'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_trunk_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'eth',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'default_template': 'no',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'ENABLE_OSPF',
        'profile_key': 'enable_ospf',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_AREA_ID',
        'profile_key': 'ospf_area_id',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'default_template': '0.0.0.0',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 15,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_BFD_MODE',
        'profile_key': 'ospf_bfd_mode',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('no_change', 'enable', 'disable'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_COST',
        'profile_key': 'ospf_cost',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_DEAD_INTERVAL',
        'profile_key': 'ospf_dead_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_HELLO_INTERVAL',
        'profile_key': 'ospf_hello_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_MTU_IGNORE',
        'profile_key': 'ospf_mtu_ignore',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_NETWORK_TYPE',
        'profile_key': 'ospf_network_type',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('no_change', 'broadcast', 'point_to_point'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_PASSIVE_MODE',
        'profile_key': 'ospf_passive_mode',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'enum',
        'valid_values': ('no_change', 'passive', 'no_passive'),
        'default_template': 'no_change',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_PRIORITY',
        'profile_key': 'ospf_priority',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 0,
        'max_value': 255,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_RETRANSMIT_INTERVAL',
        'profile_key': 'ospf_retransmit_interval',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 65535,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_SHUTDOWN',
        'profile_key': 'ospf_shutdown',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_TAG',
        'profile_key': 'ospf_tag',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 20,
    },
    {
        'parent_template': 'int_vlan',
        'parent_nvpair': 'OSPF_TRANSMIT_DELAY',
        'profile_key': 'ospf_transmit_delay',
        'applicable_interface_type': 'svi',
        'applicable_mode': 'vlan',
        'type': 'integer',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_value': 1,
        'max_value': 450,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_access_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'access',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'ACL_FILTER',
        'profile_key': 'acl_filter',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'string',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
        'min_length': 1,
        'max_length': 64,
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_RECEIVE',
        'profile_key': 'disable_lldp_receive',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_LLDP_TRANSMIT',
        'profile_key': 'disable_lldp_transmit',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'default_template': False,
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_QOS_STATS',
        'profile_key': 'disable_qos_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'DISABLE_QUEUING_STATS',
        'profile_key': 'disable_queuing_stats',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'boolean',
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'GUARD_MODE',
        'profile_key': 'guard_mode',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('root', 'none', 'loop', 'no'),
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
    {
        'parent_template': 'int_vpc_trunk_host',
        'parent_nvpair': 'SPANNING_TREE_PORT_TYPE',
        'profile_key': 'spanning_tree_port_type',
        'applicable_interface_type': 'vpc',
        'applicable_mode': 'trunk',
        'type': 'enum',
        'valid_values': ('no', 'network', 'normal'),
        'mechanism': 'passthrough',
        'min_ndfc_version': '12.6.0.267',
    },
)


def registered_profile_keys(parent_template):
    """Public profile keys registered for a parent (thin: exact set, no name heuristic)."""
    return {b['profile_key'] for b in BINDING_TABLE if b['parent_template'] == parent_template}


def resolve_binding(parent_template, profile_key):
    """Exactly one binding for (parent_template, profile_key), or None."""
    hits = [b for b in BINDING_TABLE
            if b['parent_template'] == parent_template and b['profile_key'] == profile_key]
    return hits[0] if len(hits) == 1 else None


def resolve_by_nvpair(parent_template, parent_nvpair):
    hits = [b for b in BINDING_TABLE
            if b['parent_template'] == parent_template and b['parent_nvpair'] == parent_nvpair]
    return hits[0] if len(hits) == 1 else None
