---
# This playbook can be used to execute integration tests for
# the role located in:
#
# tests/integration/targets/dcnm_bootflash
#
# Modify the hosts and vars sections with details for your testing
# setup and uncomment the testcase you want to run.
#
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # testcase: dcnm_bootflash_deleted_specific
    # testcase: dcnm_bootflash_deleted_wildcard
    # testcase: dcnm_bootflash_query_specific
    # testcase: dcnm_bootflash_query_wildcard
    switch_username: admin
    switch_password: "password-secret"
    switch1: 192.168.1.2
    switch2: 192.168.1.3
    # The vars below are included in the role's defaults/main.yaml
    # If it is desired to override the defaults, uncomment and
    # modify these.
    # switch1_file1: air.ndfc_ut
    # switch1_file2: earth.ndfc_ut
    # switch1_file3: fire.ndfc_ut
    # switch1_file4: water.ndfc_ut
    # switch2_file1: black.ndfc_ut
    # switch2_file2: blue.ndfc_ut
    # switch2_file3: green.ndfc_ut
    # switch2_file4: red.ndfc_ut
    # wildcard_filepath: "*:/*.ndfc_ut"

  roles:
    - dcnm_bootflash
