"""PO-HOST-E1-OFFLINE: focused tests for PVLAN host on a regular port-channel (int_port_channel_pvlan_host).

NOT LIVE TESTED. Real main(); only the external boundary is mocked, through the EXISTING Ethernet
harness (test_dcnm_intf_pvlan_harness.FakeController) plus the smallest subclass that teaches it the
port-channel create path. No new controller, switch or framework.

SYNTHETIC DATA. Every pending/running/expected stanza below is written BY HAND from the captured
templates (host/member add() bodies) -- it is a prediction, not a controller measurement, and it is
never generated by the code under test. A fixture holding all 29 template fields does not prove the
controller's runtime defaults. The first live case (M1) is what measures all of this.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

import copy
import json

import pytest

from ansible_collections.cisco.dcnm.plugins.module_utils import interface_pvlan as P

from .test_dcnm_intf_pvlan_harness import (
    IF7,
    IF8,
    SERIAL,
    SWITCH_IP,
    TRUNK,
    FakeController,
    ok,
    preview,
    run,
    trunk_host_nv,
)

PO = "Port-channel10"  # the module-normalised name; device stanzas stay lower case
PO_ITEM_NAME = "po10"
PO_HOST = "int_port_channel_pvlan_host"
PO_MEMBER = "int_port_channel_pvlan_member"
GLOBAL_IF = "/rest/globalInterface"
DEPLOY = "/rest/globalInterface/deploy"
MODIFY = "/rest/interface/modify"
PRIMARY, SECONDARY = 2210, 2212  # candidates (ALPHA's proposal), not validated by this review

RUNNING_MEMBER = ["interface Ethernet1/7", "  switchport", "  switchport mode trunk",
                  "  switchport trunk allowed vlan none", "  spanning-tree port type edge trunk",
                  "  mtu 9216", "  shutdown"]
PO_STANZA = ["interface port-channel10", "  switchport", "  switchport mode private-vlan host",
             "  switchport private-vlan host-association 2210 2212", "  mtu 9216",
             "  spanning-tree bpduguard enable", "  spanning-tree port type edge trunk", "  shutdown"]
# PO G3 (Alpha): MEASURED member forms of the H1 creation (fixtures/pvlan_po_h1_measured.json, port-channel502 /
# Ethernet1/10), TRANSPOSED to this harness's names (port-channel10 / Ethernet1/7). The controller's expected member holds
# `channel-group N mode active` (no `force`) plus the inherited PVLAN mode and list line; the member pending holds only
# `no spanning-tree port type edge trunk` (before the parent block) and `channel-group N force mode active` + `shutdown`.
# The G1/E2 hand predictions (expected WITH force; pending withdrawing the trunk lines and adding the PVLAN lines) were
# contradicted by that measurement.
MEMBER_AFTER = ["interface ethernet1/7", "  channel-group 10 mode active", "  mtu 9216", "  shutdown", "  switchport",
                "  switchport mode private-vlan host", "  switchport private-vlan host-association 2210 2212"]
PENDING_NEW = (["interface ethernet1/7", "  no spanning-tree port type edge trunk"] + PO_STANZA
               + ["interface ethernet1/7", "  channel-group 10 force mode active", "  shutdown", "configure terminal"])


class PoController(FakeController):
    """The existing fake controller + the port-channel create path (POST globalInterface)."""

    def __init__(self):
        super(PoController, self).__init__()
        self.create_responses = []
        self.po_names = set()

    def __call__(self, mod, method, path, data=None):
        if method == "POST" and path.endswith(GLOBAL_IF):
            self.calls.append((method, path, data))
            resp = self.create_responses.pop(0) if self.create_responses else ok({})
            body = json.loads(data)
            body = body if isinstance(body, list) else [body]
            if resp.get("RETURN_CODE") in (200, 207):
                for payload in body:
                    for intf in payload["interfaces"]:
                        self.detail[intf["ifName"]] = {"policy": payload["policy"], "nvPairs": copy.deepcopy(intf["nvPairs"])}
                        self.po_names.add(intf["ifName"])
            return resp
        return super(PoController, self).__call__(mod, method, path, data)

    def _summary_list(self):
        out = super(PoController, self)._summary_list()
        for entry in out:
            if entry["ifName"] in self.po_names:
                entry["ifType"], entry["isPhysical"], entry["mode"] = "INTERFACE_PORT_CHANNEL", "False", "trunk"
        return out

    def creates(self):
        return [c for c in self.calls if c[0] == "POST" and c[1].endswith(GLOBAL_IF)]

    def deploys(self):
        return [c for c in self.calls if c[0] == "POST" and c[1].endswith(DEPLOY)]

    def writes(self):
        return [c for c in self.calls if c[0] in ("POST", "PUT", "DELETE") and "networkAttachments/query" not in c[1]
                and "/config-preview" not in c[1]]


def _as_list(body):
    return body if isinstance(body, list) else [body]


def po_item(name=PO_ITEM_NAME, deploy=True, **profile):
    prof = {"mode": "pvlan", "pvlan_mode": "host", "members": [IF7], "admin_state": False,
            "pvlan_association": [{"primary_vlan": PRIMARY, "secondary_vlan": SECONDARY}]}
    prof.update(profile)
    return {"name": name, "type": "pc", "switch": [SWITCH_IP], "deploy": deploy, "profile": prof}


def baseline_ctrl(member_nv=None):
    ctrl = PoController()
    ctrl.detail[IF7] = {"policy": TRUNK, "nvPairs": member_nv if member_nv is not None else trunk_host_nv(IF7)}
    return ctrl


def good_preview():
    return preview(PENDING_NEW, running=RUNNING_MEMBER, expected=PO_STANZA + MEMBER_AFTER)


def created_ctrl():
    """Controller state after a successful M1 (SYNTHETIC: the member policy flip is predicted)."""
    ctrl = baseline_ctrl()
    ctrl.previews = [good_preview()]
    status, result = run(ctrl, [po_item()])
    assert status == "exit", result
    nv = {"PO_ID": PO, "PC_MODE": "active", "PVLAN_MODE": "host", "CDP_ENABLE": "true", "lldpTransmit": "false",
          "lldpReceive": "false", "LACP_PORT_PRIO": "32768", "LACP_RATE": "normal", "DESC": "", "CONF": "",
          "ADMIN_STATE": "false", "INTF_NAME": IF7}
    ctrl.detail[IF7] = {"policy": PO_MEMBER, "nvPairs": nv}
    ctrl.next_invocation()
    ctrl.calls = []
    return ctrl


# ------------------------------------------------------------------ route, payload types, creation
def test_creation_real_route_payload_types_and_order():
    ctrl = baseline_ctrl()
    ctrl.previews = [good_preview()]
    status, result = run(ctrl, [po_item()])
    assert status == "exit" and result["changed"] is True, result
    assert len(ctrl.creates()) == 1 and ctrl.requests("POST", MODIFY) == []
    body = json.loads(ctrl.creates()[0][2])
    payload = body[0] if isinstance(body, list) else body
    assert payload["policy"] == PO_HOST
    nv = payload["interfaces"][0]["nvPairs"]
    # D2: declared types. LACP_PORT_PRIO is an integer; LACP_RATE and PORT_DUPLEX_MODE are strings.
    assert nv["LACP_PORT_PRIO"] == 32768 and isinstance(nv["LACP_PORT_PRIO"], int)
    assert nv["LACP_RATE"] == "normal" and nv["PORT_DUPLEX_MODE"] == "auto"
    assert nv["PC_MODE"] == "active" and nv["MTU"] == "jumbo" and nv["SPEED"] == "Auto" and nv["BPDUGUARD_ENABLED"] == "true"
    assert nv["ADMIN_STATE"] == "false" and nv["MEMBER_INTERFACES"] == IF7 and nv["PO_ID"] == PO
    # HOST:424 evaluates PVLAN_NATIVE_VLAN even in host mode: the neutral wire form is the empty STRING
    # measured in the Ethernet writes; never the integer 1 (1 != "1") and never an omitted key.
    assert nv["PVLAN_NATIVE_VLAN"] == "" and isinstance(nv["PVLAN_NATIVE_VLAN"], str)
    assert nv["PVLAN_ALLOWED_VLANS"] == "" and nv["CONF"] == ""
    assert P.pairs_from_wire(nv["ASSOCIATION_LIST"], "ASSOCIATION_LIST") == [(PRIMARY, SECONDARY)]
    # preview generated BEFORE the deploy; nothing outside the legacy path
    order = ctrl.order()
    assert order.index("PREVIEW") < order.index("DEPLOY") and ctrl.manage() == []
    # the parent writes the member: no direct write to the member interface
    entries = [i["ifName"] for c in ctrl.creates() for p in _as_list(json.loads(c[2])) for i in p["interfaces"]]
    assert entries == [PO], "only the parent is created; the member appears solely inside MEMBER_INTERFACES"
    assert result.get("pvlan_gate")[0]["targets"][PO] == "deploy"


def test_creation_without_deploy_sends_no_preview_and_no_deploy():
    ctrl = baseline_ctrl()
    status, result = run(ctrl, [po_item(deploy=False)])
    assert status == "exit" and len(ctrl.creates()) == 1 and ctrl.deploys() == [] and ctrl.order() == []


# ------------------------------------------------------------------ identical repetition / merged / replaced
def test_identical_repetition_is_a_noop_without_any_write():
    ctrl = created_ctrl()
    status, result = run(ctrl, [po_item()])
    assert status == "exit" and result["changed"] is False, result
    assert ctrl.writes() == [] and ctrl.deploys() == []


def test_merged_omitted_keys_preserve_have():
    ctrl = created_ctrl()
    ctrl.detail[PO]["nvPairs"]["DESC"] = "kept from have"
    ctrl.detail[PO]["nvPairs"]["MTU"] = "default"  # a HAVE value the playbook never mentions
    status, result = run(ctrl, [po_item()], state="merged")
    assert status == "exit" and result["changed"] is False and ctrl.writes() == []
    assert ctrl.detail[PO]["nvPairs"]["DESC"] == "kept from have" and ctrl.detail[PO]["nvPairs"]["MTU"] == "default"


def test_replaced_states_the_complete_model_and_updates_only_the_differing_keys():
    # G1 (scope change): `replaced` on an existing PVLAN port-channel is an UPDATE to the complete model (E6
    # contract): an omitted description is the template declaration "". E2 refused every update.
    ctrl = created_ctrl()
    ctrl.detail[PO]["nvPairs"]["DESC"] = "kept from have"
    status, result = run(ctrl, [po_item(deploy=False)], state="replaced")
    assert status == "exit" and result["changed"] is True, result
    bodies = [json.loads(c[2]) for c in ctrl.calls if c[0] == "POST" and "bulk-update" in c[1] or c[1].endswith(MODIFY)]
    sent = [i["nvPairs"] for b in bodies for p in (b if isinstance(b, list) else [b]) for i in p["interfaces"]]
    assert len(sent) == 1 and sent[0]["DESC"] == "" and sent[0]["ASSOCIATION_LIST"] == ctrl.detail[PO]["nvPairs"]["ASSOCIATION_LIST"]
    assert result["diff"][0]["replaced"][0]["interfaces"][0]["nvPairs"] == {"DESC": ""}, "the diff is exactly the change"
    assert ctrl.creates() == [] and ctrl.deploys() == []


def test_update_of_an_existing_port_channel_changes_only_the_association():
    # G1 (scope change): the association of an existing host port-channel is updated (one modify, no create).
    ctrl = created_ctrl()
    cfg = po_item(deploy=False, pvlan_association=[{"primary_vlan": PRIMARY, "secondary_vlan": 2213}])
    status, result = run(ctrl, [cfg], state="replaced")
    assert status == "exit" and result["changed"] is True, result
    assert ctrl.creates() == [] and ctrl.deploys() == []
    assert P.pairs_from_wire(ctrl.detail[PO]["nvPairs"]["ASSOCIATION_LIST"], "ASSOCIATION_LIST") == [(2210, 2213)]


def test_existing_port_channel_with_another_policy_is_not_converted():
    ctrl = created_ctrl()
    ctrl.detail[PO]["policy"] = "int_port_channel_trunk_host"
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and "not implemented" in result["msg"] and ctrl.writes() == []


# ------------------------------------------------------------------ scope: refused before any write
@pytest.mark.parametrize("profile, needle", [
    # G1: promiscuous/trunk secondary are implemented; the lists must match the mode
    ({"pvlan_mode": "promiscuous"}, "pvlan_association is not valid for pvlan_mode 'promiscuous'"),
    ({"pvlan_mode": "bogus"}, "pvlan_mode must be one of"),
    ({"members": [IF7, IF8]}, "exactly one member"),
    ({"members": []}, "exactly one member"),
    ({"members": ["Port-channel5"]}, "physical Ethernet"),
    ({"pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2211}, {"primary_vlan": 2220, "secondary_vlan": 2221}]}, "at most one association"),
    ({"pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2210}]}, "itself"),
    ({"speed": "10Gb"}, "not implemented"),
    ({"cmds": ["no ip redirects"]}, "not implemented"),
    ({"native_vlan": "10"}, "valid only for pvlan_mode trunk"),
    ({"pvlan_mapping": [{"primary_vlan": 2210, "secondary_vlans": "2211"}]}, "pvlan_mapping is not valid for pvlan_mode 'host'"),
    ({"pc_mode": "bogus"}, "pc_mode"),
])
def test_out_of_scope_is_refused_before_any_request(profile, needle):
    ctrl = baseline_ctrl()
    status, result = run(ctrl, [po_item(**profile)])
    assert status == "fail" and needle in result["msg"], result
    assert ctrl.writes() == [], "nothing may be written for a refused request"


def test_missing_required_fields_are_refused():
    for drop in ("members", "pvlan_association", "pvlan_mode"):
        item = po_item()
        item["profile"].pop(drop)
        status, result = run(baseline_ctrl(), [item])
        assert status == "fail", drop


# G1 (scope change): `deleted` of the port-channel itself is implemented (test_dcnm_intf_pvlan_po_g1.py); `overridden`
# stays refused.
@pytest.mark.parametrize("state", ["overridden"])
def test_states_not_implemented_for_a_pvlan_port_channel(state):
    ctrl = created_ctrl()
    status, result = run(ctrl, [po_item()], state=state)
    assert status == "fail" and "not implemented" in result["msg"] and ctrl.writes() == []


def test_ndfc11_gets_an_explicit_error_without_claiming_impossibility():
    status, result = run(baseline_ctrl(), [po_item()], version=(11, "11.5.3"))
    assert status == "fail" and "not implemented for this controller version" in result["msg"]
    assert "impossible" not in result["msg"] and "unsupported by NDFC" not in result["msg"]


def test_check_mode_creation_is_refused_without_writing():
    ctrl = baseline_ctrl()
    status, result = run(ctrl, [po_item()], check_mode=True)
    assert status == "fail" and "check mode" in result["msg"] and ctrl.writes() == []


# ------------------------------------------------------------------ identity: absence vs failed/ambiguous reads
def test_summary_lists_the_po_but_detail_is_empty_is_ambiguous_not_absent():
    ctrl = baseline_ctrl()
    ctrl.detail[PO] = {"policy": PO_HOST, "nvPairs": {}}
    ctrl.po_names.add(PO)
    real = ctrl._detail_entry
    ctrl.read_failures = set()
    # detail answers [] for the Po while the summary still lists it
    original = ctrl.__class__.__call__

    def hide_detail(self, mod, method, path, data=None):
        if "/rest/interface?serialNumber=" in path and "&ifName=" + PO in path:
            self.calls.append((method, path, data))
            return ok([])
        return original(self, mod, method, path, data)

    ctrl.__class__ = type("Hidden", (PoController,), {"__call__": hide_detail})
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and ctrl.creates() == [], result


def test_unreadable_summary_is_refused_before_any_write():
    ctrl = baseline_ctrl()
    ctrl.read_failures = {"/rest/interface/detail?serialNumber="}
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and ctrl.writes() == [], result


def test_stray_live_policy_on_an_absent_port_channel_is_refused():
    ctrl = baseline_ctrl()
    ctrl.policies_extra = [{"entityName": PO, "entityType": "INTERFACE", "templateName": "int_port_channel_trunk_host",
                            "source": "", "deleted": False, "policyId": "POLICY-900", "serialNumber": SERIAL}]
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and "live policy" in result["msg"] and ctrl.writes() == []


# ------------------------------------------------------------------ members: baseline, conflicts, direct mutation (D4)
def test_member_that_is_not_administratively_down_is_refused():
    nv = trunk_host_nv(IF7)
    nv["ADMIN_STATE"] = "true"
    status, result = run(baseline_ctrl(nv), [po_item()])
    assert status == "fail" and "administratively down" in result["msg"]


def test_member_with_freeform_conf_is_refused():
    nv = trunk_host_nv(IF7)
    nv["CONF"] = "no cdp enable"
    status, result = run(baseline_ctrl(nv), [po_item()])
    assert status == "fail" and "freeform" in result["msg"]


def test_member_absent_from_the_controller_is_refused_not_preprovisioned():
    ctrl = PoController()
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and "preprovisioning is not implemented" in result["msg"] and ctrl.writes() == []


def test_member_already_in_another_port_channel_is_refused():
    ctrl = baseline_ctrl()
    ctrl.detail[IF7]["policy"] = "int_port_channel_trunk_member_11_1"
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and "already a port-channel member" in result["msg"] and ctrl.writes() == []


def test_member_owned_by_a_network_attachment_is_refused():
    ctrl = baseline_ctrl()
    ctrl.policies_extra = [{"entityName": IF7, "entityType": "INTERFACE", "templateName": "Config_Profile",
                            "source": "OVERLAY", "deleted": False, "policyId": "POLICY-901", "serialNumber": SERIAL}]
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and ctrl.writes() == []


def test_member_with_a_baseline_policy_outside_the_model_is_refused():
    ctrl = baseline_ctrl()
    ctrl.detail[IF7]["policy"] = "int_access_host"
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and "not covered" in result["msg"] and ctrl.writes() == []


def test_direct_mutation_of_a_pvlan_member_is_refused_for_any_policy():
    ctrl = created_ctrl()
    for item in ({"name": IF7, "type": "eth", "switch": [SWITCH_IP], "deploy": True, "profile": {"mode": "trunk"}},
                 {"name": IF7, "type": "eth", "switch": [SWITCH_IP], "deploy": True,
                  "profile": {"mode": "pvlan", "pvlan_mode": "host"}}):
        status, result = run(ctrl, [item], state="replaced")
        assert status == "fail" and "managed by the parent" in result["msg"] or "port-channel or vPC member" in result["msg"], result
        assert ctrl.writes() == []


def test_member_admin_state_is_preserved_in_the_model_not_forced_up():
    nv = trunk_host_nv(IF7)
    member = P.po_member_nvpairs(P.po_host_nvpairs(
        {"pvlan_mode": "host", "members": [IF7], "pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}],
         "admin_state": True}, PO), nv)
    assert member["ADMIN_STATE"] == "false", "parent no-shutdown does not bring a shutdown member up (inherited)"
    assert "shutdown" in P.render(PO_MEMBER, member).scalars


# ------------------------------------------------------------------ the pre-deploy gate
def run_with_preview(pv, **kw):
    ctrl = baseline_ctrl()
    ctrl.previews = [pv]
    status, result = run(ctrl, [po_item()], **kw)
    return ctrl, status, result


def test_gate_foreign_line_on_the_parent_refuses_and_never_deploys():
    pend = list(PENDING_NEW)
    pend.insert(1, "  switchport trunk allowed vlan 10")  # trunk CLI nobody asked for
    ctrl, status, result = run_with_preview(preview(pend, running=RUNNING_MEMBER, expected=PO_STANZA + MEMBER_AFTER))
    assert status == "fail" and "unmodeled command" in result["msg"], result
    assert ctrl.deploys() == [] and len(ctrl.creates()) == 1
    assert "ALREADY changed" in result["msg"], "the pending intent must be reported, not rolled back"


def test_gate_pending_for_another_interface_refuses():
    pend = PENDING_NEW + ["interface Ethernet1/9", "  no shutdown"]
    ctrl, status, result = run_with_preview(preview(pend, running=RUNNING_MEMBER, expected=PO_STANZA + MEMBER_AFTER))
    assert status == "fail" and "outside this deploy batch" in result["msg"] and ctrl.deploys() == []


def test_gate_pending_with_global_lines_refuses():
    ctrl, status, result = run_with_preview(preview(["feature lacp"] + PENDING_NEW, running=RUNNING_MEMBER, expected=PO_STANZA + MEMBER_AFTER))
    assert status == "fail" and "outside interface scope" in result["msg"] and ctrl.deploys() == []


def test_gate_expected_config_disagreeing_with_the_intent_refuses():
    wrong = [l.replace("2212", "2299") for l in PO_STANZA]
    ctrl, status, result = run_with_preview(preview(PENDING_NEW, running=RUNNING_MEMBER, expected=wrong + MEMBER_AFTER))
    assert status == "fail" and "disagrees with the intended state" in result["msg"] and ctrl.deploys() == []


def test_gate_member_trunk_cli_not_withdrawn_refuses():
    # G3: the trunk switchport lines go away WITH `channel-group N force` (measured H1); the one trunk line the measured
    # pending withdraws explicitly is the spanning-tree port type, so its absence is the refusal under test.
    pend = [l for l in PENDING_NEW if "no spanning-tree port type edge trunk" not in l]
    ctrl, status, result = run_with_preview(preview(pend, running=RUNNING_MEMBER, expected=PO_STANZA + MEMBER_AFTER))
    assert status == "fail" and "withdrawal of 'spanning-tree port type edge trunk' is absent" in result["msg"] and ctrl.deploys() == []


def test_gate_member_capability_lines_are_not_waved_through():
    pend = PENDING_NEW[:-1] + ["  ptp"] + PENDING_NEW[-1:]  # inside the member block (G3: the measured pending ends with `configure terminal`)
    ctrl, status, result = run_with_preview(preview(pend, running=RUNNING_MEMBER, expected=PO_STANZA + MEMBER_AFTER))
    assert status == "fail" and "ptp" in result["msg"] and ctrl.deploys() == []


def test_gate_failed_or_malformed_preview_never_deploys():
    ctrl = baseline_ctrl()
    ctrl.read_failures = {"/config-preview/"}
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and ctrl.deploys() == [] and len(ctrl.creates()) == 1
    ctrl2 = baseline_ctrl()
    ctrl2.previews = [ok([])]
    status, result = run(ctrl2, [po_item()])
    assert status == "fail" and ctrl2.deploys() == []


def test_gate_absence_is_accepted_only_with_exactly_one_expected_stanza():
    # a NEW parent has no running stanza; zero or two EXPECTED stanzas are never accepted
    for expected in (MEMBER_AFTER, PO_STANZA + PO_STANZA + MEMBER_AFTER):
        ctrl, status, result = run_with_preview(preview(PENDING_NEW, running=RUNNING_MEMBER, expected=expected))
        assert status == "fail" and ctrl.deploys() == [], expected


def test_gate_running_stanza_present_for_a_new_parent_is_treated_as_unexpected():
    running = RUNNING_MEMBER + ["interface port-channel10", "  switchport"]
    ctrl, status, result = run_with_preview(preview(PENDING_NEW, running=running, expected=PO_STANZA + MEMBER_AFTER))
    assert status == "fail" and ctrl.deploys() == [], result


# ------------------------------------------------------------------ responses: create and deploy
def test_create_207_with_an_error_item_fails_and_is_not_deployed():
    ctrl = baseline_ctrl()
    ctrl.create_responses = [{"RETURN_CODE": 207, "MESSAGE": "Multi-Status", "DATA": [
        {"reportItemType": "ERROR", "message": "template refused", "entity": "%s~%s" % (SERIAL, PO)}]}]
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and ctrl.deploys() == [] and ctrl.order() == []


def test_create_207_all_success_naming_the_port_channel_is_accepted():
    ctrl = baseline_ctrl()
    ctrl.previews = [good_preview()]
    ctrl.create_responses = [{"RETURN_CODE": 207, "MESSAGE": "Multi-Status", "DATA": [
        {"reportItemType": "SUCCESS", "message": "ok", "entity": "%s~%s" % (SERIAL, PO)}]}]
    status, result = run(ctrl, [po_item()])
    assert status == "exit" and result["changed"] is True


def test_create_207_success_for_another_entity_only_is_not_accepted():
    ctrl = baseline_ctrl()
    ctrl.create_responses = [{"RETURN_CODE": 207, "MESSAGE": "Multi-Status", "DATA": [
        {"reportItemType": "SUCCESS", "message": "ok", "entity": "%s~port-channel99" % SERIAL}]}]
    status, result = run(ctrl, [po_item()])
    assert status == "fail"
    # it must fail AT the create: had it been accepted, the gate would have asked for a preview
    assert ctrl.order() == [] and ctrl.deploys() == [], "the create answer was accepted although it does not name the port-channel"


@pytest.mark.parametrize("deploy_resp", [
    {"RETURN_CODE": 207, "MESSAGE": "Multi-Status", "DATA": [{"reportItemType": "ERROR", "message": "device rejected"}]},
    {"RETURN_CODE": 200, "MESSAGE": "OK", "DATA": [{"reportItemType": "ERROR", "message": "device rejected"}]},
    {"RETURN_CODE": 500, "MESSAGE": "Internal Server Error", "DATA": {"message": "boom"}},
])
def test_deploy_error_responses_fail_and_keep_the_response(deploy_resp):
    ctrl = baseline_ctrl()
    ctrl.previews = [good_preview()]
    ctrl.deploy_responses = [deploy_resp]
    status, result = run(ctrl, [po_item()])
    assert status == "fail" and len(ctrl.deploys()) == 1, result


# ------------------------------------------------------------------ Ethernet and non-PVLAN Po are untouched
def test_non_pvlan_port_channel_uses_the_unchanged_generic_path():
    ctrl = PoController()
    item = {"name": "po11", "type": "pc", "switch": [SWITCH_IP], "deploy": False,
            "profile": {"mode": "trunk", "members": [IF8], "allowed_vlans": "none"}}
    status, result = run(ctrl, [item])
    assert status == "exit" and len(ctrl.creates()) == 1
    sent = json.loads(ctrl.creates()[0][2])
    sent = sent[0] if isinstance(sent, list) else sent
    assert sent["policy"] != PO_HOST and sent["policy"] == "int_port_channel_trunk_host"


# ------------------------------------------------------------------ interface_pvlan units
def test_ethernet_vocabulary_and_defaults_are_unchanged_by_the_po_tables():
    assert P.VOCABULARY_POLICIES == ("int_pvlan_host", "int_trunk_host")
    assert PO_HOST not in P.VOCABULARY_POLICIES and PO_MEMBER not in P.VOCABULARY_POLICIES
    assert P.PO_VOCABULARY_POLICIES == (PO_HOST, PO_MEMBER)


def test_assess_target_absent_ok_defaults_to_the_e6_behaviour():
    entry = {"runningConfig": ["interface Ethernet1/7"], "expectedConfig": PO_STANZA, "pendingConfig": PO_STANZA, "status": "Out-of-Sync"}
    model = P.render(PO_HOST, P.po_host_nvpairs(
        {"pvlan_mode": "host", "members": [IF7], "pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}],
         "admin_state": False}, PO))
    assert model.modeled
    body = [l.strip() for l in PO_STANZA[1:]]  # split_blocks hands the assessor stripped lines
    decision, _detail = P.assess_target(body, entry, PO, model, P.transition_vocabulary(None, (PO_HOST, {})))
    assert decision == "refuse", "without absent_ok a missing running stanza is a refusal (E6 unchanged)"
    decision, found = P.assess_target(body, entry, PO, model, P.transition_vocabulary(None, (PO_HOST, {})), absent_ok=True)
    assert decision == "deploy", found


def test_reconcile_po_creation_noop_and_refusals():
    raw = {"pvlan_mode": "host", "members": [IF7], "pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}],
           "admin_state": False}
    created = P.reconcile_po("merged", raw, PO, None, None)
    assert created["creates"] and not created["update"] and created["blocked"] == []
    same = P.reconcile_po("replaced", raw, PO, PO_HOST, copy.deepcopy(created["nv"]))
    assert same["blocked"] == [] and not same["creates"] and same["nv"] == created["nv"]
    other = P.reconcile_po("replaced", raw, PO, "int_port_channel_trunk_host", {})
    assert other["blocked"] and "converting" in other["blocked"][0]


def test_po_models_are_unmodeled_outside_the_first_delivery():
    nv = P.po_host_nvpairs({"pvlan_mode": "host", "members": [IF7],
                            "pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}]}, PO)
    assert P.render(PO_HOST, nv).modeled
    # G1: PVLAN_MODE promiscuous is modeled now; a non-trunk mode with a native VLAN still is not
    for key, value in (("SPEED", "10Gb"), ("PVLAN_MODE", "bogus"), ("PVLAN_NATIVE_VLAN", "1"),
                       ("QUEUING_POLICY", "q"), ("spanningTreePortType", "network")):
        bad = dict(nv)
        bad[key] = value
        assert not P.render(PO_HOST, bad).modeled, key


# ------------------------------------------------------------------ models M1/M2 (NOT RUN live)
def _load_model(name):
    import os
    import yaml
    path = os.path.join(os.path.dirname(__file__), "fixtures", "pvlan_po_host_models", name)
    play = yaml.safe_load(open(path))[0]
    args = copy.deepcopy(play["tasks"][0]["cisco.dcnm.dcnm_interface"])
    values = {"po_fabric": "test_fabric", "po_switch": SWITCH_IP, "po_name": PO_ITEM_NAME, "po_member": IF7}

    def sub(node):
        if isinstance(node, dict):
            return dict((k, sub(v)) for k, v in node.items())
        if isinstance(node, list):
            return [sub(v) for v in node]
        if isinstance(node, str) and node.startswith("{{") and node.endswith("}}"):
            return values[node[2:-2].strip()]
        return node
    return sub(args)


def test_models_m1_and_m2_are_valid_and_run_through_the_real_argspec():
    m1, m2 = _load_model("M1_po_host_create.yml"), _load_model("M2_po_host_repeat.yml")
    assert m1 == m2, "M2 is the IDENTICAL model of M1"
    ctrl = baseline_ctrl()
    ctrl.previews = [good_preview()]
    status, result = run(ctrl, m1["config"], state=m1["state"])
    assert status == "exit" and result["changed"] is True and len(ctrl.creates()) == 1
    ctrl2 = created_ctrl()
    status, result = run(ctrl2, m2["config"], state=m2["state"])
    assert status == "exit" and result["changed"] is False and ctrl2.writes() == []


def test_models_carry_only_placeholders_and_declare_not_run():
    import os
    d = os.path.join(os.path.dirname(__file__), "fixtures", "pvlan_po_host_models")
    for name in ("vars_po_host_e1.yml", "M1_po_host_create.yml", "M2_po_host_repeat.yml"):
        text = open(os.path.join(d, name)).read()
        assert "NOT RUN" in text, name
        for real in ("192.168.", "SAL0000PO01", "FAB1", "Leaf"):
            assert real not in text, (name, real)


# ------------------------------------------------------------------ existing routes that could reach a PVLAN Po/member
# Found by probing (evidence/.../tools/probe_unprotected_routes.py): before the guard these four reached the
# controller (markdelete / modify / deploy). Each is now refused before any write.
def _eth(name, mode="trunk"):
    return {"name": name, "type": "eth", "switch": [SWITCH_IP], "deploy": False, "profile": {"mode": mode}}


def _po_trunk():
    return {"name": PO_ITEM_NAME, "type": "pc", "switch": [SWITCH_IP], "deploy": False,
            "profile": {"mode": "trunk", "members": [IF7]}}


@pytest.mark.parametrize("label, state, build", [
    ("overridden naming an unrelated interface", "overridden", lambda: [_eth(IF8)]),
    ("deleted naming the port-channel through a non-PVLAN profile", "deleted", lambda: [_po_trunk()]),
    ("replaced converting the port-channel to trunk", "replaced", lambda: [_po_trunk()]),
    ("deleted naming the member", "deleted", lambda: [_eth(IF7)]),
])
def test_existing_routes_cannot_reset_delete_or_convert_a_pvlan_port_channel_or_member(label, state, build):
    ctrl = created_ctrl()
    ctrl.detail[IF8] = {"policy": TRUNK, "nvPairs": trunk_host_nv(IF8)}
    status, result = run(ctrl, build(), state=state)
    assert status == "fail" and "not implemented" in result["msg"] and ctrl.writes() == [], (label, result.get("msg"))


def test_negative_control_the_same_flows_without_a_pvlan_po_are_unchanged():
    ctrl = baseline_ctrl()
    nv = trunk_host_nv(IF8)
    nv["ALLOWED_VLANS"] = "10"  # not the default, so the reset is a real change
    ctrl.detail[IF8] = {"policy": TRUNK, "nvPairs": nv}
    status, result = run(ctrl, [_eth(IF8)], state="deleted")
    assert status == "exit" and ctrl.writes() != [], "an ordinary delete must still reach the controller"


def test_two_port_channels_of_one_playbook_cannot_share_a_member():
    ctrl = baseline_ctrl()
    status, result = run(ctrl, [po_item(), po_item(name="po11")])
    assert status == "fail" and "also assigns it to port-channel" in result["msg"], result
    assert ctrl.writes() == []
