"""PO G1 (Alpha, PR725-PVLAN-PO-P-001): focused tests for the four PVLAN modes on a regular port-channel with ONE member.

NOT LIVE TESTED. Real main(); only the external boundary is mocked, through the EXISTING harness (FakeController +
the E2 PoController). Every pending/running/expected stanza below is SYNTHETIC, written BY HAND from the captured
templates (host add() HOST:416-560 incl. the member 'Inherited Commands' child; member add() MEMBER:109-205) and,
for the member released by a deletion, from the regular-Po deletion MEASURED in pr725-state-withdrawal W2/G25. They
are predictions, never generated by the code under test; the first live case of each mode measures them.
Each test fails on the E2 source (create-host-only), which refuses these modes, updates and the deletion.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

import copy
import json
import os

import pytest

from ansible_collections.cisco.dcnm.plugins.module_utils import interface_pvlan as P

from .test_dcnm_intf_pvlan_harness import IF7, IF8, SWITCH_IP, TRUNK, ok, preview, run, trunk_host_nv
from .test_dcnm_intf_pvlan_po_host import PO, PO_HOST, PO_ITEM_NAME, PO_MEMBER, RUNNING_MEMBER, PoController

MARKDELETE = "/rest/interface/markdelete"
BULK = "/rest/interface/modify"


def markdelete_ok(data):
    """G4-R1: the MEASURED mark-delete success answer (HR wire log, NDFC 12.6.0.267): 200/OK with DATA.message and one
    `value` item per deleted interface naming its serial and IfName."""
    body = json.loads(data)
    body = body if isinstance(body, list) else [body]
    return ok(
        {
            "message": "Interface deleted successfully",
            "value": [{"interfaceType": "INTERFACE_PORT_CHANNEL", "serialNumber": i.get("serialNumber"), "IfName": i.get("ifName")} for i in body],
        }
    )


class PoLifecycleController(PoController):
    """E2 PoController + a markdelete that removes the parent and leaves the member on the released trunk policy (the
    G25-measured regular-Po behaviour; for a PVLAN member this is the PREDICTION under test, not a measurement)."""

    def __init__(self):
        super(PoLifecycleController, self).__init__()
        self.release_member = True
        self.inherited_child = True

    def __call__(self, mod, method, path, data=None):
        if method == "DELETE" and path.endswith(MARKDELETE):
            self.calls.append((method, path, data))
            body = json.loads(data)
            for intf in body if isinstance(body, list) else [body]:
                name = intf.get("ifName")
                parent = self.detail.pop(name, None)
                self.po_names.discard(name)
                if parent and self.release_member:
                    for member in str(parent["nvPairs"].get("MEMBER_INTERFACES", "")).split(","):
                        if member.strip():
                            nv = trunk_host_nv(member.strip())
                            nv["ADMIN_STATE"] = "false"
                            self.detail[member.strip()] = {"policy": TRUNK, "nvPairs": nv}
            return markdelete_ok(data)
        return super(PoLifecycleController, self).__call__(mod, method, path, data)

    def _policies(self):
        """G4: the member policies in the MEASURED H1 shape (fixtures/pvlan_po_h1_measured.json): the
        int_port_channel_pvlan_member carries the port-channel as source, and the parent's 'Inherited Commands' int_eth
        child (source = the port-channel) sits on the same member. The base harness gives every policy source ''."""
        out = super(PoLifecycleController, self)._policies()
        children = []
        for p in out:
            if p["templateName"] == PO_MEMBER:
                po = str(self.detail[p["entityName"]]["nvPairs"].get("PO_ID", "")).lower()
                p["source"] = po
                if self.inherited_child:
                    children.append(
                        dict(p, templateName="int_eth", source=po, policyId=p["policyId"] + "-inherited", priority=512, description="Inherited Commands")
                    )
        return out + children

    def bulk_bodies(self):
        return [json.loads(c[2]) for c in self.calls if c[0] == "POST" and c[1].endswith(BULK)]

    def markdeletes(self):
        return [c for c in self.calls if c[0] == "DELETE" and c[1].endswith(MARKDELETE)]


def item(mode, deploy=True, **profile):
    prof = {"mode": "pvlan", "pvlan_mode": mode, "members": [IF7], "admin_state": False}
    prof.update(profile)
    return {"name": PO_ITEM_NAME, "type": "pc", "switch": [SWITCH_IP], "deploy": deploy, "profile": prof}


MAP_2212 = [{"primary_vlan": 2210, "secondary_vlans": "2212"}]
MAP_2211 = [{"primary_vlan": 2210, "secondary_vlans": "2211"}]


def po_stanza(mode, lines):
    return (
        ["interface port-channel10", "  switchport", "  switchport mode private-vlan %s" % mode]
        + ["  " + l for l in lines]
        + ["  mtu 9216", "  spanning-tree bpduguard enable", "  spanning-tree port type edge trunk", "  shutdown"]
    )


def member_stanza(mode, lines):
    # G3: the MEASURED expected member form (H1, host), transposed: persisted `channel-group N mode active` (no force) and
    # the parent's PVLAN mode/list lines. For the other modes this is the same form, NOT measured (G5: SYNTHETIC, inferred).
    return [
        "interface ethernet1/7",
        "  channel-group 10 mode active",
        "  mtu 9216",
        "  shutdown",
        "  switchport",
        "  switchport mode private-vlan %s" % mode,
    ] + ["  " + l for l in lines]


# G6: trunk secondary is created only from a member PREPARED as access (or routed); EXP-1 MEASURED that a switchport-trunk member
# is rejected by the device. The prepared access member is the measured EXP-1 branch A one (fixtures/pvlan_po_ts_exp1_measured.json).
EXP1 = json.load(open(os.path.join(os.path.dirname(__file__), "fixtures", "pvlan_po_ts_exp1_measured.json")))
ACCESS = "int_access_host"
RUNNING_ACCESS = ["interface Ethernet1/7", "  shutdown", "  spanning-tree port type edge", "  mtu 9216"]


def prepared_access_nv(ifname=IF7):
    nv = dict((k, v) for k, v in EXP1["branches"]["A"]["member_before"]["intent"]["Ethernet1/8"]["nvPairs"].items() if k != "POLICY_ID")
    nv["INTF_NAME"] = ifname
    return nv


def create_preview(mode, lines):
    # G3: the MEASURED pending form of a member creation (H1, host), transposed: the trunk spanning-tree withdrawal before
    # the parent block, then `channel-group N force mode active` + `shutdown`. G5: for promiscuous and trunk promiscuous this form
    # is now MEASURED (P1, TP1); G6: trunk secondary uses the MEASURED access-member form (EXP-1 A: `no spanning-tree port type
    # edge`), transposed to the harness port-channel10/Ethernet1/7.
    ts = mode == "trunk secondary"
    pend = (
        ["interface ethernet1/7", "  no spanning-tree port type edge" if ts else "  no spanning-tree port type edge trunk"]
        + po_stanza(mode, lines)
        + ["interface ethernet1/7", "  channel-group 10 force mode active", "  shutdown", "configure terminal"]
    )
    return preview(pend, running=RUNNING_ACCESS if ts else RUNNING_MEMBER, expected=po_stanza(mode, lines) + member_stanza(mode, lines))


def baseline(mode=None):
    ctrl = PoLifecycleController()
    if mode == "trunk secondary":
        ctrl.detail[IF7] = {"policy": ACCESS, "nvPairs": prepared_access_nv(IF7)}
    else:
        ctrl.detail[IF7] = {"policy": TRUNK, "nvPairs": trunk_host_nv(IF7)}
    return ctrl


def created(mode, lines, **profile):
    """Controller holding an EXISTING port-channel of `mode` with its member (SYNTHETIC member flip, as in E2's
    created_ctrl). G5: every mode is created through main() (host: measured force form; the others: inferred, with the
    synthetic create_preview)."""
    ctrl = baseline(mode)
    ctrl.previews = [create_preview(mode, lines)]
    status, result = run(ctrl, [item(mode, **profile)], state="replaced")
    assert status == "exit" and result["changed"] is True, result
    parent = ctrl.detail[PO]["nvPairs"]
    ctrl.detail[IF7] = {
        "policy": PO_MEMBER,
        "nvPairs": {
            "PO_ID": PO,
            "PC_MODE": "active",
            "PVLAN_MODE": mode,
            "CDP_ENABLE": "true",
            "lldpTransmit": "false",
            "lldpReceive": "false",
            "LACP_PORT_PRIO": "32768",
            "LACP_RATE": "normal",
            "DESC": "",
            "CONF": "",
            "ADMIN_STATE": "false",
            "INTF_NAME": IF7,
        },
    }
    assert parent["PVLAN_MODE"] == mode
    ctrl.next_invocation()
    ctrl.calls = []
    return ctrl


# ------------------------------------------------------------------ creation in the four modes
@pytest.mark.parametrize(
    "mode, profile, lines, check",
    [
        (
            "promiscuous",
            {"pvlan_mapping": MAP_2212},
            ["switchport private-vlan mapping 2210 2212"],
            lambda nv: P.pairs_from_wire(nv["MAPPING_LIST"], "MAPPING_LIST") == [(2210, 2212)] and nv["ASSOCIATION_LIST"] == "",
        ),
        (
            "trunk promiscuous",
            {"pvlan_mapping": [{"primary_vlan": 2210, "secondary_vlans": "2211-2212"}], "native_vlan": "2301", "allowed_vlans": "2301"},
            [
                "switchport private-vlan trunk native vlan 2301",
                "switchport private-vlan trunk allowed vlan 2301",
                "switchport private-vlan mapping trunk 2210 2211",
                "switchport private-vlan mapping trunk 2210 2212",
            ],
            lambda nv: nv["PVLAN_NATIVE_VLAN"] == "2301"
            and nv["PVLAN_ALLOWED_VLANS"] == "2301"
            and P.pairs_from_wire(nv["MAPPING_LIST"], "MAPPING_LIST") == [(2210, 2211), (2210, 2212)],
        ),
        (
            "trunk secondary",
            {"pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}], "native_vlan": "2301", "allowed_vlans": "2301"},
            [
                "switchport private-vlan trunk native vlan 2301",
                "switchport private-vlan trunk allowed vlan 2301",
                "switchport private-vlan association trunk 2210 2212",
            ],
            lambda nv: P.pairs_from_wire(nv["ASSOCIATION_LIST"], "ASSOCIATION_LIST") == [(2210, 2212)] and nv["MAPPING_LIST"] == "",
        ),
        (
            "host",
            {"pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}]},
            ["switchport private-vlan host-association 2210 2212"],
            lambda nv: nv["PVLAN_NATIVE_VLAN"] == "" and nv["PVLAN_ALLOWED_VLANS"] == "",
        ),
    ],
)
def test_creation_in_each_mode_payload_types_gate_and_member_model(mode, profile, lines, check):
    # G5: the four modes run through main(); host on the measured force form, the others on the inferred one.
    # G6: trunk secondary from the prepared access member.
    ctrl = baseline(mode)
    ctrl.previews = [create_preview(mode, lines)]
    status, result = run(ctrl, [item(mode, **profile)], state="replaced")
    assert status == "exit" and result["changed"] is True, result.get("msg")
    assert len(ctrl.creates()) == 1 and len(ctrl.deploys()) == 1 and ctrl.bulk_bodies() == []
    body = json.loads(ctrl.creates()[0][2])
    body = body[0] if isinstance(body, list) else body
    nv = body["interfaces"][0]["nvPairs"]
    assert body["policy"] == PO_HOST and nv["PVLAN_MODE"] == mode and nv["ADMIN_STATE"] == "false" and check(nv)
    assert nv["MEMBER_INTERFACES"] == IF7 and isinstance(nv["LACP_PORT_PRIO"], int)
    assert not any(k.startswith("__") for k in nv), "the member model's internal keys never reach a payload"
    assert result["pvlan_gate"][0]["targets"][PO] == "deploy"


def test_member_model_includes_the_inherited_commands_child_and_rejects_its_absence():
    # The inherited list line is part of the MEASURED expected member (H1); without it the gate refuses (G3: host).
    lines = ["switchport private-vlan host-association 2210 2212"]
    ctrl = baseline()
    pv = create_preview("host", lines)
    entry = pv["DATA"][0]
    entry["expectedConfig"] = po_stanza("host", lines) + [l for l in member_stanza("host", lines) if "host-association" not in l]
    ctrl.previews = [pv]
    status, result = run(ctrl, [item("host", pvlan_association=[{"primary_vlan": 2210, "secondary_vlan": 2212}])], state="replaced")
    assert status == "fail" and "Ethernet1/7" in result["msg"] and "pair 2210/2212" in result["msg"] and ctrl.deploys() == []


def test_trunk_secondary_creation_with_a_community_secondary_is_refused_before_any_write():
    # G5: the CREATION itself is refused by the community typing (G3 refused it earlier, as an unmeasured mode); the
    # update of an existing trunk secondary port-channel to a community secondary is refused too.
    ctrl = baseline("trunk secondary")
    status, result = run(ctrl, [item("trunk secondary", pvlan_association=[{"primary_vlan": 2210, "secondary_vlan": 2211}])], state="replaced")
    assert status == "fail" and "community" in result["msg"] and ctrl.writes() == []
    ctrl = created(
        "trunk secondary", ["switchport private-vlan association trunk 2210 2212"], pvlan_association=[{"primary_vlan": 2210, "secondary_vlan": 2212}]
    )
    status, result = run(ctrl, [item("trunk secondary", pvlan_association=[{"primary_vlan": 2210, "secondary_vlan": 2211}])], state="replaced")
    assert status == "fail" and "community" in result["msg"] and ctrl.writes() == []


def test_creation_requires_the_active_list_and_the_member():
    for prof in ({"pvlan_mapping": None}, {}):
        p = dict({"pvlan_mode": "promiscuous", "members": [IF7], "admin_state": False}, **prof)
        p = dict((k, v) for k, v in p.items() if v is not None)
        status, result = run(
            baseline(), [{"name": PO_ITEM_NAME, "type": "pc", "switch": [SWITCH_IP], "deploy": True, "profile": dict(p, mode="pvlan")}], state="replaced"
        )
        assert status == "fail" and "pvlan_mapping is required" in result["msg"]
    status, result = run(baseline(), [item("promiscuous", pvlan_mapping=MAP_2212, members=None)], state="replaced")
    assert status == "fail"


# ------------------------------------------------------------------ PO-P2 / PO-P3 / PO-P4 (promiscuous)
P2_PREVIEW_LINES = ["switchport private-vlan mapping 2210 2211", "switchport private-vlan mapping 2210 2212"]


def p2_preview():
    run_po = po_stanza("promiscuous", ["switchport private-vlan mapping 2210 2212"])
    run_m = member_stanza("promiscuous", ["switchport private-vlan mapping 2210 2212"])
    pend = ["interface port-channel10", "  switchport private-vlan mapping 2210 2211", "interface Ethernet1/7", "  switchport private-vlan mapping 2210 2211"]
    return preview(pend, running=run_po + run_m, expected=po_stanza("promiscuous", P2_PREVIEW_LINES) + member_stanza("promiscuous", P2_PREVIEW_LINES))


def p2_item():
    # PO-P2: only mode, pvlan_mode and the mapping to add; members, admin_state and companions omitted (preserved).
    return {
        "name": PO_ITEM_NAME,
        "type": "pc",
        "switch": [SWITCH_IP],
        "deploy": True,
        "profile": {"mode": "pvlan", "pvlan_mode": "promiscuous", "pvlan_mapping": MAP_2211},
    }


def test_p2_merged_adds_2211_keeps_2212_and_every_omitted_field_and_reports_only_the_delta():
    ctrl = created("promiscuous", ["switchport private-vlan mapping 2210 2212"], pvlan_mapping=MAP_2212)
    have = copy.deepcopy(ctrl.detail[PO]["nvPairs"])
    ctrl.previews = [p2_preview()]
    status, result = run(ctrl, [p2_item()], state="merged")
    assert status == "exit" and result["changed"] is True, result.get("msg")
    assert ctrl.creates() == [] and len(ctrl.bulk_bodies()) == 1 and len(ctrl.deploys()) == 1
    sent = ctrl.bulk_bodies()[0][0]["interfaces"][0]["nvPairs"]
    assert P.pairs_from_wire(sent["MAPPING_LIST"], "MAPPING_LIST") == [(2210, 2211), (2210, 2212)]
    for key in ("ADMIN_STATE", "DESC", "MEMBER_INTERFACES", "PC_MODE", "MTU", "BPDUGUARD_ENABLED", "LACP_PORT_PRIO"):
        assert sent[key] == have[key], key
    assert result["diff"][0]["merged"][0]["interfaces"][0]["nvPairs"] == {"MAPPING_LIST": sent["MAPPING_LIST"]}
    assert result["pvlan_gate"][0]["targets"][PO] == "deploy"


def test_p3_identical_repeat_of_p2_writes_nothing():
    ctrl = created("promiscuous", ["switchport private-vlan mapping 2210 2212"], pvlan_mapping=MAP_2212)
    ctrl.previews = [p2_preview()]
    status, _result = run(ctrl, [p2_item()], state="merged")
    assert status == "exit"
    ctrl.next_invocation()
    ctrl.calls = []
    status, result = run(ctrl, [p2_item()], state="merged")
    assert status == "exit" and result["changed"] is False, result
    assert ctrl.writes() == [] and ctrl.deploys() == [] and ctrl.creates() == []


def test_p4_partial_removal_from_promiscuous_is_refused_before_any_write_as_protection():
    ctrl = created("promiscuous", ["switchport private-vlan mapping 2210 2212"], pvlan_mapping=MAP_2212)
    ctrl.previews = [p2_preview()]
    run(ctrl, [p2_item()], state="merged")
    ctrl.next_invocation()
    ctrl.calls = []
    status, result = run(ctrl, [item("promiscuous", pvlan_mapping=MAP_2212)], state="replaced")
    assert status == "fail" and "promiscuous mapping that keeps other secondaries is blocked" in result["msg"]
    assert "NOT measured" in result["msg"], "the Po behaviour is not claimed as the Ethernet bug"
    assert ctrl.writes() == [] and ctrl.deploys() == []
    assert P.pairs_from_wire(ctrl.detail[PO]["nvPairs"]["MAPPING_LIST"], "MAPPING_LIST") == [(2210, 2211), (2210, 2212)]


def test_trunk_promiscuous_partial_removal_is_not_blocked():
    raw = {"pvlan_mode": "trunk promiscuous", "pvlan_mapping": [{"primary_vlan": 2210, "secondary_vlans": "2212"}]}
    have = P.po_host_nvpairs(dict(raw, members=[IF7], pvlan_mapping=[{"primary_vlan": 2210, "secondary_vlans": "2211-2212"}]), PO)
    out = P.reconcile_po("replaced", raw, PO, PO_HOST, have)
    assert out["blocked"] == [] and out["update"] and list(out["changed"]) == ["MAPPING_LIST"]


# ------------------------------------------------------------------ scope refusals of an existing port-channel
@pytest.mark.parametrize(
    "raw, needle",
    [
        ({"pvlan_mode": "host", "pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}]}, "changing pvlan_mode"),
        ({"pvlan_mode": "promiscuous", "pvlan_mapping": MAP_2212, "members": [IF8]}, "changing the members"),
    ],
)
def test_mode_and_member_changes_of_an_existing_port_channel_are_refused(raw, needle):
    have = P.po_host_nvpairs({"pvlan_mode": "promiscuous", "members": [IF7], "pvlan_mapping": MAP_2212}, PO)
    out = P.reconcile_po("merged", raw, PO, PO_HOST, have)
    assert out["blocked"] and needle in out["blocked"][0] and not out["update"]


def test_unclassifiable_have_field_blocks_a_full_set_update():
    have = P.po_host_nvpairs({"pvlan_mode": "promiscuous", "members": [IF7], "pvlan_mapping": MAP_2212}, PO)
    have["SOMETHING_NEW"] = "x"
    out = P.reconcile_po("merged", {"pvlan_mode": "promiscuous", "pvlan_mapping": MAP_2211}, PO, PO_HOST, have)
    assert out["blocked"] and "cannot classify" in out["blocked"][0]


def test_merged_without_members_on_an_existing_port_channel_keeps_its_member():
    have = P.po_host_nvpairs({"pvlan_mode": "promiscuous", "members": [IF7], "pvlan_mapping": MAP_2212}, PO)
    out = P.reconcile_po("merged", {"pvlan_mode": "promiscuous", "pvlan_mapping": MAP_2211}, PO, PO_HOST, have)
    assert out["blocked"] == [] and out["members"] == IF7 and out["nv"]["MEMBER_INTERFACES"] == IF7


# ------------------------------------------------------------------ PO-PR: deletion of the own port-channel
def delete_preview(mode, lines):
    run_cfg = po_stanza(mode, lines) + member_stanza(mode, lines)
    released = [
        "interface Ethernet1/7",
        "  switchport",
        "  switchport mode trunk",
        "  switchport trunk allowed vlan none",
        "  spanning-tree port type edge trunk",
        "  mtu 9216",
        "  shutdown",
    ]
    pend = (
        ["no interface port-channel10", "interface Ethernet1/7", "  no switchport mode private-vlan %s" % mode]
        + ["  no " + l for l in lines]
        # G3: the running member holds the PERSISTED `channel-group 10 mode active` (measured form), so the synthetic
        # withdrawal names that line. The deletion pending of a DEPLOYED PVLAN port-channel is NOT MEASURED (HR deleted a
        # never-deployed one); this stays a synthetic prediction.
        + ["  no channel-group 10 mode active", "  switchport mode trunk", "  switchport trunk allowed vlan none", "  spanning-tree port type edge trunk"]
    )
    return preview(pend, running=run_cfg, expected=released)


def del_item(**profile):
    out = {"name": PO_ITEM_NAME, "type": "pc", "switch": [SWITCH_IP], "deploy": True}
    if profile:
        out["profile"] = profile
    return out


def test_pr_deletion_markdeletes_deploys_and_verifies_the_member_release_without_writing_it():
    lines = ["switchport private-vlan mapping 2210 2212"]
    ctrl = created("promiscuous", lines, pvlan_mapping=MAP_2212)
    ctrl.previews = [delete_preview("promiscuous", lines)]
    status, result = run(ctrl, [del_item()], state="deleted")
    assert status == "exit" and result["changed"] is True, result.get("msg")
    assert len(ctrl.markdeletes()) == 1 and len(ctrl.deploys()) == 1 and ctrl.bulk_bodies() == []
    assert PO not in ctrl.detail and ctrl.detail[IF7]["policy"] == TRUNK
    assert result["pvlan_gate"][0]["targets"][PO] == "deploy"
    deployed = json.loads(ctrl.deploys()[0][2])
    assert [d["ifName"] for d in deployed] == [PO], "only the parent is deployed; the member is released by the controller"


def test_pr_deletion_is_refused_when_the_expected_member_state_is_not_the_released_trunk():
    lines = ["switchport private-vlan mapping 2210 2212"]
    ctrl = created("promiscuous", lines, pvlan_mapping=MAP_2212)
    pv = delete_preview("promiscuous", lines)
    pv["DATA"][0]["expectedConfig"] = [l for l in pv["DATA"][0]["expectedConfig"] if l != "  shutdown"]  # would come up
    ctrl.previews = [pv]
    status, result = run(ctrl, [del_item()], state="deleted")
    assert status == "fail" and "disagrees with the intended state" in result["msg"] and ctrl.deploys() == []
    assert "ALREADY changed" in result["msg"], "the mark-delete is reported, never rolled back"


def test_pr_deletion_is_refused_when_the_parent_is_still_expected():
    lines = ["switchport private-vlan mapping 2210 2212"]
    ctrl = created("promiscuous", lines, pvlan_mapping=MAP_2212)
    pv = delete_preview("promiscuous", lines)
    pv["DATA"][0]["expectedConfig"] = po_stanza("promiscuous", lines) + pv["DATA"][0]["expectedConfig"]
    ctrl.previews = [pv]
    status, result = run(ctrl, [del_item()], state="deleted")
    assert status == "fail" and "still holds" in result["msg"] and ctrl.deploys() == []


def test_pr_deletion_fails_loud_when_the_member_is_not_released_and_never_rewrites_it():
    lines = ["switchport private-vlan mapping 2210 2212"]
    ctrl = created("promiscuous", lines, pvlan_mapping=MAP_2212)
    ctrl.release_member = False  # the controller leaves the member policy in place
    ctrl.previews = [delete_preview("promiscuous", lines)]
    status, result = run(ctrl, [del_item()], state="deleted")
    # G4: the pre-deploy member release finds the member still holding the PVLAN member policy and stops: no modify of a
    # member that was not released, and no deploy.
    assert status == "fail" and "member release failed" in result["msg"] and "int_port_channel_pvlan_member" in result["msg"]
    assert ctrl.bulk_bodies() == [] and ctrl.deploys() == [], "the member is never rewritten to hide a failed release"


@pytest.mark.parametrize(
    "prep, needle, kw",
    [
        (lambda c: c.detail[IF7]["nvPairs"].__setitem__("ADMIN_STATE", "true"), "not administratively down", {}),
        (lambda c: None, "check mode", {"check_mode": True}),
    ],
)
def test_pr_deletion_preconditions_refuse_before_any_write(prep, needle, kw):
    ctrl = created("promiscuous", ["switchport private-vlan mapping 2210 2212"], pvlan_mapping=MAP_2212)
    prep(ctrl)
    status, result = run(ctrl, [del_item()], state="deleted", **kw)
    assert status == "fail" and needle in result["msg"] and ctrl.writes() == []


def test_pr_deletion_without_deploy_is_refused():
    ctrl = created("promiscuous", ["switchport private-vlan mapping 2210 2212"], pvlan_mapping=MAP_2212)
    d = del_item()
    d["deploy"] = False
    status, result = run(ctrl, [d], state="deleted")
    assert status == "fail" and "without deploy" in result["msg"] and ctrl.writes() == []


def test_deleting_a_non_pvlan_port_channel_is_unchanged():
    ctrl = PoLifecycleController()
    ctrl.detail[PO] = {"policy": "int_port_channel_trunk_host", "nvPairs": {"MEMBER_INTERFACES": IF8, "PO_ID": PO}}
    ctrl.po_names.add(PO)
    status, result = run(ctrl, [del_item()], state="deleted")
    assert status == "exit" and len(ctrl.markdeletes()) == 1 and "pvlan_gate" not in result


def test_helper_released_member_model_is_the_measured_trunk_baseline_shut():
    model = P.render(P.TRUNK_HOST_POLICY, P.PO_RELEASED_MEMBER_NV)
    assert model.modeled and model.scalars == {
        "switchport",
        "switchport mode trunk",
        "switchport trunk allowed vlan none",
        "spanning-tree port type edge trunk",
        "mtu 9216",
        "shutdown",
    }


def test_pr_deletion_fails_loud_when_a_child_policy_still_claims_the_member():
    lines = ["switchport private-vlan mapping 2210 2212"]
    ctrl = created("promiscuous", lines, pvlan_mapping=MAP_2212)
    # The host template creates the member's children with the port-channel as source (HOST:536-560); one survives.
    ctrl.policies_extra = [
        {
            "entityName": IF7,
            "entityType": "INTERFACE",
            "templateName": "int_eth",
            "source": PO,
            "deleted": False,
            "policyId": "POLICY-990001",
            "priority": 512,
            "serialNumber": "x",
        }
    ]
    ctrl.previews = [delete_preview("promiscuous", lines)]
    status, result = run(ctrl, [del_item()], state="deleted")
    assert status == "fail" and "live policies still reference the port-channel" in result["msg"] and "int_eth" in result["msg"]
    assert ctrl.bulk_bodies() == []


def test_ra_recovery_deletes_a_created_but_never_deployed_port_channel_and_still_deploys():
    # R-A: the creation was refused by the gate AFTER the create, so the controller holds the parent and member intent
    # but the device never received it: running = the member's trunk baseline, expected = the released model.
    # G3: host (the measured creation mode).
    lines = ["switchport private-vlan host-association 2210 2212"]
    ctrl = baseline()
    ctrl.previews = [create_preview("host", lines)]
    ctrl.previews[0]["DATA"][0]["expectedConfig"] = po_stanza("host", lines)
    status, result = run(ctrl, [item("host", pvlan_association=[{"primary_vlan": 2210, "secondary_vlan": 2212}])], state="replaced")
    assert status == "fail" and len(ctrl.creates()) == 1 and ctrl.deploys() == []
    ctrl.detail[IF7] = {
        "policy": PO_MEMBER,
        "nvPairs": {"PO_ID": PO, "PVLAN_MODE": "host", "ADMIN_STATE": "false", "DESC": "", "CONF": "", "INTF_NAME": IF7},
    }
    ctrl.next_invocation()
    ctrl.calls = []
    released = [
        "interface Ethernet1/7",
        "  switchport",
        "  switchport mode trunk",
        "  switchport trunk allowed vlan none",
        "  spanning-tree port type edge trunk",
        "  mtu 9216",
        "  shutdown",
    ]
    ctrl.previews = [preview([], running=released, expected=released)]
    status, result = run(ctrl, [del_item()], state="deleted")
    assert status == "exit" and result["changed"] is True, result.get("msg")
    assert len(ctrl.markdeletes()) == 1 and len(ctrl.deploys()) == 1, "an empty pending never skips the deploy of a deletion"
    assert PO not in ctrl.detail and ctrl.detail[IF7]["policy"] == TRUNK and ctrl.bulk_bodies() == []


def test_h3_merged_description_only_preserves_the_association_and_the_member():
    ctrl = created("host", ["switchport private-vlan host-association 2210 2212"], pvlan_association=[{"primary_vlan": 2210, "secondary_vlan": 2212}])
    have = copy.deepcopy(ctrl.detail[PO]["nvPairs"])
    lines = ["switchport private-vlan host-association 2210 2212"]
    run_cfg = po_stanza("host", lines) + member_stanza("host", lines)
    exp = list(run_cfg)
    exp.insert(1, "  description PR725-POH-DESC-1")
    ctrl.previews = [preview(["interface port-channel10", "  description PR725-POH-DESC-1"], running=run_cfg, expected=exp)]
    cfg = {
        "name": PO_ITEM_NAME,
        "type": "pc",
        "switch": [SWITCH_IP],
        "deploy": True,
        "profile": {"mode": "pvlan", "pvlan_mode": "host", "description": "PR725-POH-DESC-1"},
    }
    status, result = run(ctrl, [cfg], state="merged")
    assert status == "exit" and result["changed"] is True, result.get("msg")
    sent = ctrl.bulk_bodies()[0][0]["interfaces"][0]["nvPairs"]
    assert sent["DESC"] == "PR725-POH-DESC-1"
    for key in ("ASSOCIATION_LIST", "MEMBER_INTERFACES", "ADMIN_STATE", "PC_MODE", "MAPPING_LIST"):
        assert sent[key] == have[key], key
    assert result["diff"][0]["merged"][0]["interfaces"][0]["nvPairs"] == {"DESC": "PR725-POH-DESC-1"}


def test_h4_replaced_host_association_swap_is_a_full_set_update():
    have = P.po_host_nvpairs({"pvlan_mode": "host", "members": [IF7], "pvlan_association": [{"primary_vlan": 2210, "secondary_vlan": 2212}]}, PO)
    raw = {"pvlan_mode": "host", "pvlan_association": [{"primary_vlan": 2410, "secondary_vlan": 2412}]}
    out = P.reconcile_po("replaced", raw, PO, PO_HOST, have)
    assert out["blocked"] == [] and out["update"] and list(out["changed"]) == ["ASSOCIATION_LIST"]
    assert P.pairs_from_wire(out["nv"]["ASSOCIATION_LIST"], "ASSOCIATION_LIST") == [(2410, 2412)]
    assert out["nv"]["MEMBER_INTERFACES"] == IF7
