---
- name: Play for ndfc
  hosts: ndfc
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    ansible_switch1: 192.168.10.211
    ansible_switch2: 192.168.10.212
    ansible_switch3: 192.168.10.213
    ansible_it_fabric: cisco_test_fabric1
    deploy: false
    switch_username: admin
    switch_password: admin!@#

  roles:
    - dcnm_inventory
  tags: always
