all:
  vars:
    ansible_user: "admin"
    ansible_password: "password-ndfc"
    switch_password: "password-switch"
    ansible_python_interpreter: python
    ansible_httpapi_validate_certs: False
    ansible_httpapi_use_ssl: True
  children:
    ndfc:
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: cisco.dcnm.dcnm
      hosts:
        192.168.1.1:
