all:
  vars:
    ansible_user: "admin"
    ansible_password: "password-secret"
    ansible_python_interpreter: python
    ansible_httpapi_validate_certs: False
    ansible_httpapi_use_ssl: True
  children:
    dcnm:
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: cisco.dcnm.dcnm
      hosts:
        nac-ndfc1:
          ansible_host: 10.10.5.1