---
# This playbook can be used to execute integration tests for
# the role located in:
#
# tests/integration/targets/dcnm_interface
#
# Modify the vars section with details for your testing setup.
#
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # Uncomment testcase to run a specific test
    # testcase: dcnm_intf_sani*
    # IT_CONTEXT: true
    test_data_common:
      fabric: fabric_name
      deploy: false
      check_deploy: false
      switch1: 192.168.10.210
      switch2: 192.168.10.204
      serial1: "sn1"
      serial2: "sn2"
      sw_sn:
        "192.168.10.210": "sn1"
        "192.168.10.204": "sn2"
      eth_intf2: Ethernet1/2
      eth_intf3: Ethernet1/3
      eth_intf4: Ethernet1/4
      eth_intf5: Ethernet1/5
      eth_intf6: Ethernet1/6
      eth_intf7: Ethernet1/7
      eth_intf8: Ethernet1/8
      eth_intf9: Ethernet1/9
      eth_intf10: Ethernet1/10
      eth_intf11: Ethernet1/11
      eth_intf12: Ethernet1/12
      eth_intf13: Ethernet1/13
      eth_intf14: Ethernet1/14
      eth_intf15: Ethernet1/15
      eth_intf16: Ethernet1/16
      eth_intf17: Ethernet1/17
      eth_intf18: Ethernet1/18
      eth_intf19: Ethernet1/19
      eth_intf20: Ethernet1/20
      eth_intf21: Ethernet1/21
      eth_intf22: Ethernet1/22
      eth_intf23: Ethernet1/23
      eth_intf24: Ethernet1/24
      parent_intf1: Ethernet1/25
      sub_intf1: Ethernet1/25.100
      parent_intf2: Ethernet1/26
      sub_intf2: Ethernet1/26.100
  roles:
    - dcnm_interface