---
# This playbook can be used to execute integration tests for
# the role located in:
#
# tests/integration/targets/dcnm_policy
#
# Modify the vars section with details for your testing setup.
#
- name: Play for dcnm
  hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    # Uncomment 'testcase:' to run a specific test under 'tests/integration/targets/dcnm_policy/tests/dcnm'
    # testcase: dcnm_policy_with*
    ansible_it_fabric: cisco_test_fabric1
    ansible_switch1: 192.168.10.211
    ansible_sw1_sno: 92ZK8YLTSKY
    ansible_switch2: 192.168.10.212
    ansible_sw2_sno: 97XSGCMXTDU

  roles:
    - dcnm_policy
