# This is a basic workflow to help you get started with Actions

name: NDFC_IT_Tests

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - id: step1
        run: echo "Mike Test"
